#!/usr/bin/env python3
"""Verified Tunisia/foreign research batch checked on 2026-09-25."""

from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "verified_batches" / "batch_2026_09_25_06.csv"

RECORDS = [
    {
        "organization_key": "comelit r d tunisie",
        "sector": "R&D, logiciel embarqué, IoT, cloud, systèmes de sécurité et IA appliquée",
        "target_roles": "Embedded Linux Developer junior; ingénieur C/C++ junior; Software Engineer junior; ingénieur IA embarquée; Cloud Developer junior; QA/Test Engineer",
        "match_score_10": "8.8",
        "match_reason": "Une offre actuelle cible précisément un jeune ingénieur C/C++ sous Linux. Le candidat maîtrise C++, Python et le logiciel, et Comelit mène aussi des projets IA embarquée. Le principal écart concerne l'expérience pratique encore limitée en kernel, drivers et cross-compilation.",
        "junior_status": "Oui",
        "junior_evidence": "La page LinkedIn officielle Comelit R&D Tunisia décrit explicitement son offre Embedded Linux Developer comme une opportunité junior/early-career et documente plusieurs stages récents en C++, Linux et IA embarquée.",
        "active_jobs": "Embedded Linux Developer (C/C++) — Tunisie — publié environ 1 mois, page entreprise active le 2026-09-25 — candidature: olfa.basly@comelit.it — https://tn.linkedin.com/in/comelit-r-d-tunisia-534296217 | Quality Assurance Test Engineer — Tunisie — publication visible, mais 2-3 ans demandés — même page.",
        "linkedin_contact_name": "Comelit R&D Tunisia",
        "linkedin_contact_role": "Page officielle de l'équipe R&D et canal de recrutement local",
        "linkedin_profile": "https://tn.linkedin.com/in/comelit-r-d-tunisia-534296217",
        "contact_verification": "Page locale active, avec publications datant d'un mois et de quelques heures sur le recrutement et la croissance de l'équipe.",
        "verified_email": "olfa.basly@comelit.it",
        "email_status": "Adresse publiée directement par la page officielle Comelit R&D Tunisia dans l'offre Embedded Linux Developer actuelle. L'adresse cred@comelit.it du CSV n'est pas utilisée faute de vérification récente.",
        "application_channel": "mailto:olfa.basly@comelit.it | https://tn.linkedin.com/in/comelit-r-d-tunisia-534296217",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Anglais",
        "potential_score_100": "88",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Poste situé en Tunisie, site R&D d'Ariana.",
        "sources": "https://tn.linkedin.com/in/comelit-r-d-tunisia-534296217 | https://www.linkedin.com/posts/comelit-r-d-tunisia-534296217_embedded-software-developer-responsibilities-activity-7308079850534154244-dTTn | https://comelitgroup.it/lavora-con-noi/",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — offre junior C/C++ Linux actuelle et email publié",
        "notes": "Très haute priorité. Adapter le CV pour placer C++, Linux, programmation orientée objet, Git et résolution de problèmes avant le full-stack. Ne pas prétendre maîtriser les drivers ou le kernel ; montrer la volonté d'approfondir.",
        "email_subject": "Application – Junior Embedded Linux Developer (C/C++)",
        "email_body": "Dear Ms Basly,\n\nI am applying for the Embedded Linux Developer (C/C++) position at Comelit R&D Tunisia. I recently graduated as a Computer Engineer from ENSI and I am looking for a first role where I can build reliable software close to real products and hardware.\n\nI have strong foundations in C++, Python, Java, object-oriented programming, databases, APIs and Git. During my final-year project at Linedata, I helped modernise a financial product with AI agents, taking the work from business understanding to software integration. This strengthened my problem-solving discipline, autonomy and ability to learn unfamiliar systems quickly.\n\nComelit's combination of Linux, embedded software and applied AI particularly attracts me. While I am still developing deeper hands-on expertise in kernel internals, drivers and cross-compilation, I bring the core C/C++ and software-engineering skills, curiosity and commitment expected from an early-career engineer. I would be highly motivated to grow within your international R&D environment.\n\nPlease find my CV attached. I would welcome the opportunity to discuss my application.\n\nKind regards,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Hello, I am a recent ENSI Computer Engineering graduate applying for Comelit R&D Tunisia's Junior Embedded Linux Developer role. My background includes C++, Python, Linux fundamentals, software engineering and applied AI. I would be glad to connect with your team.",
        "linkedin_followup": "Hello, thank you for connecting. I have sent my application to Ms Basly for the Junior Embedded Linux Developer role. I highlighted my C++/Python foundations, software project experience and motivation to deepen embedded Linux, drivers and system integration. I would be grateful if my profile could be considered by the R&D team.",
    },
    {
        "organization_key": "cyclope ai",
        "sector": "Intelligence artificielle, Computer Vision, Deep Learning et logiciels pour infrastructures routières",
        "target_roles": "Junior Data Scientist; Computer Vision Engineer junior; ML/AI Engineer junior; Data Engineer junior; backend/full-stack developer",
        "match_score_10": "8.2",
        "match_reason": "Python, machine learning, développement logiciel et intérêt pour l'IA correspondent aux équipes Data Science et produit. Le profil ne démontre toutefois pas encore une spécialisation poussée en Computer Vision ni une expérience industrielle routière.",
        "junior_status": "Non vérifiable",
        "junior_evidence": "La page carrière invite en permanence les Data Scientists, développeurs et Product Owners à envoyer une candidature spontanée, sans préciser le niveau d'expérience ni un programme graduate.",
        "active_jobs": "Aucune offre nominative junior n'est affichée sur la page officielle le 2026-09-25. Candidature spontanée officiellement ouverte pour Data Scientists, Devs, Sales et PO — https://cyclope.ai/fr/jobs",
        "linkedin_contact_name": "Fekhr Eddine Keddous",
        "linkedin_contact_role": "Ingénieur systèmes embarqués — Cyclope.ai",
        "linkedin_profile": "https://fr.linkedin.com/in/fekhr-eddine-keddous-bb2ba212b",
        "contact_verification": "Profil public actuel Cyclope.ai et contact technique pertinent ; aucune personne RH actuelle clairement vérifiable n'a été trouvée.",
        "verified_email": "Aucun email public de recrutement vérifié",
        "email_status": "contact@cyclope.ai figure dans le CSV mais n'est pas publié comme canal de recrutement. Utiliser le formulaire officiel de candidature spontanée.",
        "application_channel": "https://cyclope.ai/fr/jobs",
        "recommended_cv": "CV_ATS_EN.pdf",
        "language": "Français",
        "potential_score_100": "49",
        "foreign_employee_status": "Non vérifiable",
        "foreign_employee_evidence": "La page carrière française ne mentionne ni visa, ni relocation, ni recrutement hors UE. Les bureaux indiqués sont à Paris/Nanterre.",
        "sources": "https://cyclope.ai/fr/jobs | https://cyclope.ai/en/jobs | https://www.linkedin.com/company/cyclope-ai/ | https://fr.linkedin.com/in/fekhr-eddine-keddous-bb2ba212b",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — candidature spontanée officielle, niveau junior et mobilité non documentés",
        "notes": "Candidature étrangère de priorité moyenne-faible. Demander explicitement l'éligibilité d'un junior tunisien et ne pas supposer de sponsoring.",
        "email_subject": "Candidature spontanée – Junior AI/Computer Vision Engineer",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite proposer ma candidature spontanée à Cyclope.ai pour une première opportunité en intelligence artificielle, Data Science ou développement logiciel.\n\nMon PFE chez Linedata a porté sur l'intégration d'agents IA dans un produit financier. Cette expérience m'a appris à transformer un besoin métier en solution logicielle, à évaluer le comportement d'un système intelligent et à penser son intégration dans un produit réel. Je maîtrise Python, C++, Java, les bases de données, le full-stack et les fondamentaux du machine learning et du deep learning.\n\nJe suis particulièrement attiré par votre utilisation d'une IA contrôlée pour améliorer la sécurité et la fluidité des routes. Même si je suis au début de ma carrière et souhaite encore approfondir la Computer Vision industrielle, je peux apporter une solide base logiciel/IA, une grande capacité d'apprentissage et une réelle sensibilité à l'impact du produit.\n\nBasé en Tunisie, je suis mobile pour la France sous réserve des formalités d'autorisation de travail. Je serais reconnaissant de savoir si un futur poste junior pourrait étudier mon profil.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Keddous, jeune diplômé ingénieur ENSI en logiciel et IA, je m'intéresse aux travaux de Cyclope.ai en Computer Vision pour la route intelligente. Mon PFE portait sur l'intégration d'agents IA dans un produit. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Keddous, merci pour la connexion. J'ai déposé une candidature spontanée chez Cyclope.ai pour un futur rôle junior IA/Data/software. Étant tunisien et mobile pour la France, pourriez-vous m'indiquer si l'équipe étudie parfois des juniors internationaux ou me conseiller le bon interlocuteur ?",
    },
    {
        "organization_key": "databy",
        "sector": "HealthTech, données de santé, Real-World Evidence, IA, Data Engineering et développement de plateformes",
        "target_roles": "Junior AI Engineer; Data Scientist junior; Data Engineer junior; Full-stack Engineer junior; DevSecOps/Cloud junior; HealthTech software engineer",
        "match_score_10": "9.0",
        "match_reason": "Clarrio.ai/DATABY combine IA, Data, full-stack et produits à fort impact. Le PFE agentique, Python, logiciel et Data correspondent directement aux équipes, et un diplômé ENSI récent travaille déjà sur les LLM chez Clarrio.",
        "junior_status": "Oui",
        "junior_evidence": "Le PFE Book 2026 proposait 14 places rémunérées en full-stack, Data Engineering, IA, QA et DevOps avec mentorat et possibilité d'offre à temps plein. L'HR Generalist indique en 2026 que l'équipe prévoit presque de doubler.",
        "active_jobs": "Aucune offre junior permanente avec intitulé et lien de candidature n'a été confirmée ouverte le 2026-09-25. La campagne PFE 2025/2026 est expirée. Fatma Krichene indique toutefois que Clarrio recrute et invite à lui envoyer le CV en message privé.",
        "linkedin_contact_name": "Fatma Krichene",
        "linkedin_contact_role": "HR Generalist — Clarrio.ai",
        "linkedin_profile": "https://tn.linkedin.com/in/fatmakrich%C3%A9n",
        "contact_verification": "Profil RH actuel Clarrio.ai, actif en 2026 et relayant directement la croissance et les candidatures.",
        "verified_email": "Aucun email public vérifié pour un emploi permanent",
        "email_status": "interns@clarrio.ai est vérifié mais réservé à la campagne PFE désormais expirée. Support@clarrio.ai du CSV n'est pas un canal de recrutement confirmé. Envoyer le CV à Fatma Krichene par LinkedIn.",
        "application_channel": "https://tn.linkedin.com/in/fatmakrich%C3%A9n | https://www.linkedin.com/company/clarrio-ai/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "82",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Implantation locale à la Technopole El Ghazala/Ariana et équipe à Tunis.",
        "sources": "https://tn.linkedin.com/in/fatmakrich%C3%A9n | https://files.thetunisianengineers.com/pfe_books_2026/PFE%20Book%20-%202026%20-%20Clarrio.pdf | https://tn.linkedin.com/in/saifeddine-bouaziz-568116226 | https://tn.linkedin.com/in/youssef-ghaoui",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — très forte adéquation et croissance RH, candidature LinkedIn recommandée",
        "notes": "Haute priorité. Ne pas envoyer à l'adresse support ni à l'adresse PFE expirée. Utiliser le message de suivi LinkedIn comme lettre courte et joindre le CV ATS général.",
        "email_subject": "Candidature junior – AI/Data/Software Engineer | HealthTech",
        "email_body": "Bonjour Madame Krichene,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite proposer ma candidature pour une première opportunité chez Clarrio.ai en IA, Data Engineering ou développement logiciel.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier grâce à des agents IA. J'y ai travaillé sur la compréhension du besoin, la conception de workflows intelligents et leur intégration dans un produit existant. Je maîtrise Python, Java, C++, le full-stack, SQL, les APIs, le machine learning, les LLM et les architectures agentiques.\n\nCe qui me motive chez Clarrio est la possibilité de mettre ces compétences au service de données de santé et de décisions qui ont un impact concret. Votre culture d'autonomie, d'apprentissage rapide et de responsabilité correspond également à la manière dont je souhaite commencer ma carrière.\n\nJe serais heureux d'être étudié pour tout besoin junior en AI, Data, software ou DevSecOps. Je joins mon CV et reste disponible pour un échange.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Madame Krichene, jeune diplômé ingénieur ENSI, je suis très intéressé par la croissance de Clarrio.ai. Mon PFE Linedata portait sur des agents IA, et mon profil couvre Python, LLM, Data et full-stack. La HealthTech donne un impact concret à ces compétences. Ravi de vous rejoindre.",
        "linkedin_followup": "Bonjour Madame Krichene, merci pour la connexion. Comme vous invitez les candidats à partager leur CV, je vous transmets le mien. Mon profil associe IA agentique, Python, Data et développement logiciel, avec un PFE réalisé chez Linedata. Je serais très motivé par un rôle junior AI/Data/Software chez Clarrio et reste disponible pour tout échange.",
    },
    {
        "organization_key": "deepshift ai",
        "sector": "IA agentique, cloud-native, OpenShift/Kubernetes, DevSecOps et solutions IA pour télécoms/IT",
        "target_roles": "Junior AI/LLM Engineer; Agentic AI Engineer junior; Python developer junior; DevSecOps/Cloud junior; RAG Engineer junior",
        "match_score_10": "9.1",
        "match_reason": "Les travaux publics de DeepShift sur les agents IA, RAG et systèmes cloud-native correspondent directement au PFE et à Python/LLM. Le candidat possède moins d'expérience pratique en OpenShift/Kubernetes/DevSecOps que les profils techniques visibles.",
        "junior_status": "Oui — stages et jeunes profils observés",
        "junior_evidence": "Plusieurs étudiants et jeunes diplômés documentent des stages/PFE récents chez DeepShift AI sur Edge AI, RAG, cybersécurité et logiciel. Un jeune profil 2026 a rejoint l'entreprise comme OpenShift Architect, ce qui prouve l'accès à des profils early-career, sans garantir un poste ouvert.",
        "active_jobs": "Aucune offre formelle actuellement ouverte avec lien et critères n'a été trouvée le 2026-09-25. Candidature spontanée recommandée auprès de la direction ou via LinkedIn.",
        "linkedin_contact_name": "Adel Amri",
        "linkedin_contact_role": "CEO / Head of DeepShift AI",
        "linkedin_profile": "Aucun URL personnel public suffisamment fiable trouvé — rechercher exactement « Adel AMRI DeepShift AI » sur LinkedIn",
        "contact_verification": "Son rôle actuel de CEO/Head est confirmé par plusieurs publications récentes d'employés et stagiaires DeepShift AI, mais le profil exact n'a pas été isolé de manière fiable.",
        "verified_email": "Aucun email public vérifié",
        "email_status": "adel.amri@deepshift-ai.eu figure dans le CSV, mais aucune source publique officielle ou publication de recrutement n'a permis de le confirmer ; ne pas l'utiliser automatiquement.",
        "application_channel": "https://www.linkedin.com/search/results/people/?keywords=Adel%20AMRI%20DeepShift%20AI",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "68",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Entreprise/équipe localisée à la Technopole El Ghazala et Raoued/Ariana.",
        "sources": "https://tn.linkedin.com/in/maram-trabelsi | https://tn.linkedin.com/in/hafedh-guenichi | https://tn.linkedin.com/in/imen-hichri-15694234a | https://tn.linkedin.com/in/mohamedkallel",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — forte adéquation et accueil juniors, aucun canal email public confirmé",
        "notes": "Haute adéquation mais petite structure et canal public limité. Contacter d'abord le CEO sur LinkedIn ou un membre technique actuel ; ne pas utiliser automatiquement l'email du CSV.",
        "email_subject": "Candidature spontanée – Junior Agentic AI / Software Engineer",
        "email_body": "Bonjour Monsieur Amri,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite proposer ma candidature à DeepShift AI pour une première opportunité autour des agents IA, des LLM/RAG ou du développement Python.\n\nMon PFE chez Linedata a précisément porté sur la modernisation d'un produit financier à l'aide d'agents IA. J'ai appris à structurer un besoin métier, concevoir des workflows agentiques et intégrer la solution dans un produit logiciel. Je maîtrise Python, Java, C++, le full-stack, les bases de données, les APIs, le machine learning et l'IA générative.\n\nLes projets DeepShift sur les agents d'entreprise, l'Edge AI et les environnements cloud-native correspondent fortement à la direction que je souhaite donner à ma carrière. Je veux approfondir OpenShift, Kubernetes et DevSecOps au contact d'une équipe qui construit des systèmes IA réellement déployables.\n\nCurieux, autonome et prêt à progresser rapidement, je serais ravi d'échanger sur tout besoin junior actuel ou futur. Mon CV est joint.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Amri, jeune diplômé ingénieur ENSI, mon PFE chez Linedata portait sur des agents IA intégrés à un produit financier. Les projets DeepShift en Agentic AI, RAG et cloud-native correspondent exactement à la direction que je vise. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Amri, merci pour la connexion. Je vous transmets mon CV pour toute opportunité junior chez DeepShift AI. Mon profil combine Python, LLM/RAG, développement logiciel et expérience récente des agents IA. Je souhaite aussi approfondir OpenShift/Kubernetes et DevSecOps dans un contexte de production. Je reste disponible pour un échange.",
    },
    {
        "organization_key": "eagle projects",
        "sector": "Ingénierie numérique, IA, robotique, Computer Vision, BIM, Digital Twin, GIS et logiciels web/mobile",
        "target_roles": "Junior AI/Robotics Engineer; Computer Vision Engineer junior; Software Engineer junior; Data/AI Engineer; développeur web/mobile; Business Analyst technique",
        "match_score_10": "8.6",
        "match_reason": "Les départements IA, robotique, web/mobile et Digital Twin correspondent au profil logiciel/IA. EagleProjects a déjà recruté un junior robotics engineer et une jeune ingénieure AI/Computer Vision. L'offre actuelle Technical Designer est toutefois orientée AutoCAD/GIS et non adaptée.",
        "junior_status": "Oui",
        "junior_evidence": "La responsable RH a documenté le passage d'un étudiant à un poste de Junior Robotics Engineer et la participation de l'entreprise aux job fairs avec offres d'emplois et stages. Une ingénieure récemment diplômée a rejoint l'équipe AI/Computer Vision.",
        "active_jobs": "Technical Designer — Tunis — publication environ 4 mois, candidature recrutement@eagleprojects.tn — https://tn.linkedin.com/in/mimouni-ameni-a940b91b1 — faible adéquation car AutoCAD/GIS requis. Aucune offre junior AI/software ouverte n'a été confirmée le 2026-09-25.",
        "linkedin_contact_name": "Ameni Mimouni",
        "linkedin_contact_role": "Ressources humaines — EagleProjects Tunisia",
        "linkedin_profile": "https://tn.linkedin.com/in/mimouni-ameni-a940b91b1",
        "contact_verification": "Profil actuel EagleProjects Tunisia, contenu RH récent et publication d'offres avec email de recrutement officiel.",
        "verified_email": "recrutement@eagleprojects.tn",
        "email_status": "Adresse publiée par l'entreprise et relayée par la responsable RH dans une offre 2026. info@eagleprojects.it du CSV est une adresse générale italienne et n'est pas prioritaire.",
        "application_channel": "mailto:recrutement@eagleprojects.tn | https://www.eagleprojects.it/en/lavora-con-noi/",
        "recommended_cv": "CV_ATS_EN.pdf",
        "language": "Anglais",
        "potential_score_100": "75",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Candidature auprès de EagleProjects Tunisia, Tunis.",
        "sources": "https://tn.linkedin.com/in/mimouni-ameni-a940b91b1 | https://tn.linkedin.com/in/ghribrihem | https://www.eagleprojects.it/en/lavora-con-noi/ | https://www.linkedin.com/posts/eagleprojects-tunisia_proud-to-share-that-eagleprojects-tunisia-activity-7395111331533570048-QMjP",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — contact RH et email actuels, recrutement junior démontré",
        "notes": "Envoyer une candidature spontanée AI/software/robotics, pas au poste Technical Designer sans AutoCAD/GIS. Le CV anglais convient à l'environnement italo-tunisien.",
        "email_subject": "Spontaneous Application – Junior AI / Software Engineer",
        "email_body": "Dear EagleProjects Tunisia Recruitment Team,\n\nI am a recent Computer Engineering graduate from ENSI seeking a first opportunity in AI, software engineering, computer vision or robotics. EagleProjects Tunisia immediately caught my attention because your R&D work connects AI and digital products to real infrastructure and industrial applications.\n\nMy final-year project at Linedata focused on modernising a financial product with AI agents. I worked from business understanding to software integration and strengthened my skills in Python, C++, Java, APIs, databases, full-stack development, machine learning and generative AI.\n\nI am particularly interested in your AI, advanced robotics and web/mobile activities. Although the current Technical Designer opening is not aligned with my background in AutoCAD/GIS, I would be highly motivated to contribute to a junior AI, computer vision or software role. I bring strong engineering fundamentals, curiosity and the ability to learn quickly in multidisciplinary teams.\n\nPlease find my CV attached. I would be glad to discuss any current or future need matching my profile.\n\nKind regards,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Madame Mimouni, jeune diplômé ingénieur ENSI, je m'intéresse aux équipes IA, robotique et software d'EagleProjects Tunisia. Mon PFE Linedata portait sur des agents IA et je maîtrise Python, C++, Java et full-stack. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Mimouni, merci pour la connexion. J'ai envoyé une candidature spontanée à recrutement@eagleprojects.tn pour un rôle junior AI/software/robotics. L'offre Technical Designer n'est pas mon meilleur alignement, mais les activités R&D IA et Computer Vision correspondent fortement à mon profil. Je reste disponible pour échanger.",
    },
]

def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(RECORDS[0]))
        writer.writeheader()
        writer.writerows(RECORDS)
    print(f"Wrote {len(RECORDS)} records to {OUT}")

if __name__ == "__main__":
    main()
