#!/usr/bin/env python3
"""Verification of six foreign targets, 2026-09-25."""
from __future__ import annotations
import csv
from pathlib import Path
OUT=Path(__file__).resolve().parent/"verified_batches"/"batch_2026_09_25_24.csv"

def r(key,name,sector,roles,score,pot,reason,junior,jobs,contact,profile,email,channel,sources,cv="CV_ATS_EN.pdf",intl="Non vérifiable"):
    return {"organization_key":key,"sector":sector,"target_roles":roles,"match_score_10":score,"potential_score_100":pot,"priority":"Haute" if float(score)>=8 else "Moyenne","match_reason":reason,"junior_status":junior,"junior_evidence":jobs,"active_jobs":jobs,"foreign_employee_status":intl,"foreign_employee_evidence":"Le statut international est limité aux éléments explicitement visibles; aucun visa n’est supposé.","linkedin_contact_name":contact,"linkedin_contact_role":"Contact actuel pertinent","linkedin_profile":profile,"contact_verification":"Profil ou page actuellement rattaché à l’organisation.","verified_email":email,"email_status":"Adresse publiée et vérifiée" if "@" in email else "Aucun email public vérifié","application_channel":channel,"recommended_cv":cv,"language":"Français","email_subject":f"Candidature spontanée — {roles.split(';')[0]} junior","email_body":f"""Bonjour,

Récemment diplômé ingénieur en informatique de l’ENSI, spécialisé en ingénierie financière, je souhaite proposer ma candidature à {name} pour une première opportunité en {roles.lower()}.

Mon PFE chez Linedata portait sur la modernisation d’un produit financier grâce à des agents IA. Je maîtrise Python, Java, C++, le développement full-stack, les bases de données, les API, le machine learning, Git et les principes CI/CD.

{reason} Je suis basé en Tunisie et ouvert au travail à distance ou à la mobilité si le cadre le permet.

Je joins mon CV et serais ravi d’échanger sur un besoin junior actuel ou futur.

Bien cordialement,
Mohamed Oussema Bahloul""","linkedin_invitation":(f"Bonjour, jeune diplômé ingénieur ENSI, mon PFE chez Linedata combinait agents IA et logiciel financier. L’activité de {name} correspond à mon profil Python, IA/Data et développement. Ravi d’échanger sur vos besoins juniors.")[:299],"linkedin_followup":f"Merci pour la connexion. Je souhaite proposer mon profil junior à {name}. Pourriez-vous m’orienter vers l’équipe qui suit les besoins IA, Data ou développement logiciel ?","sources":sources,"checked_date":"2026-09-25","verification_status":"Vérifié — screening manuel ciblé","notes":"Les offres anciennes/expérimentées sont signalées comme telles et ne doivent pas être présentées comme junior actives."}

RECORDS=[
 r("move logic","Move Logic","Generative AI, AI agents, Data Engineering, BI and automation for SMEs","Junior AI/GenAI Engineer; Data Engineer; Python Developer","9.2","66","Le positionnement GenAI sur mesure, agents d’automatisation et intégration data est extrêmement proche du PFE Linedata. La société est cependant une micro-équipe sans offre publique.","Non vérifiable — équipe de 2 à 10 personnes, sans offre publiée","Aucune offre active confirmée; candidature directe aux cofondateurs.","Meriem Djefel","https://www.linkedin.com/in/meriem-djefel/","Aucun email public vérifié","https://www.move-logic.com/","https://fr.linkedin.com/company/movelogic | https://www.linkedin.com/posts/movelogic_we-built-move-logic-around-a-simple-belief-activity-7412744945050243072-ujuY"),
 r("bmci","BMCI Mauritanie","Banking, digital financial services and FinTech innovation","Junior IT/AI Engineer; Data Analyst; Digital Transformation Analyst","8.8","58","La banque et ses initiatives FinTech correspondent à la spécialisation financière et à l’IA appliquée. La dernière offre trouvée était commerciale, exigeait deux ans et a expiré en mai 2025.","Non vérifiable pour l’IT junior; la banque recrute publiquement mais l’offre repérée demandait 2 ans","Aucune offre IT/IA active confirmée; ancienne offre Chargé d’Affaires expirée le 19/05/2025.","BMCI Mauritanie","https://www.linkedin.com/company/banque-mauritanienne-pour-le-commerce-international","Aucun email public vérifié","http://www.bmci.mr/","https://www.linkedin.com/company/banque-mauritanienne-pour-le-commerce-international | https://fr.linkedin.com/posts/banque-mauritanienne-pour-le-commerce-international_recrutement-offreemploi-banque-activity-7327709206495596545-f2in",cv="CV_ATS_Fintech_EN.pdf",intl="Partiel — candidature régionale possible, conditions pour un Tunisien non publiées"),
 r("nst groupe","NST Groupe","IT consulting, software engineering, banking systems and industrial automation","Junior Software Engineer; Full-stack Developer; QA/Automation Engineer","7.9","57","L’entreprise emploie une équipe d’ingénieurs et a accueilli des PFE tunisiens. Les offres récentes visibles demandent cinq ans et, pour la France, des candidats déjà résidents.","Oui — PFE d’ingénieur documenté; postes actuels visibles confirmés","Développeur C# finance de marché — 5 ans — Paris/résidents France; profils industriels DeltaV — 5 ans; aucune offre junior actuelle.","Houssem Jemal","https://tn.linkedin.com/in/houssem-jemal-98758348","contact@nstgroupe.com","mailto:contact@nstgroupe.com","https://www.linkedin.com/company/nst-groupe | https://tn.linkedin.com/in/houssem-jemal-98758348 | https://www.linkedin.com/posts/féryel-belhassen-b68575195_engineer-informatique-grateful-activity-7074755554128097280-A5Ev",intl="Partiel — liens Tunisie solides; missions France actuelles réservées aux résidents"),
 r("shanon technologies","Shanon Technologies","Embedded software, digital signal processing, control systems and hardware","Junior Embedded Software Engineer; Python/C++ Engineer; AI Engineer","8.2","61","Le logiciel embarqué, le DSP et les systèmes de contrôle exploitent directement C++/Python et la résolution de problèmes. Plusieurs membres tunisiens figurent dans la petite équipe, mais aucune offre n’est affichée.","Oui/partiel — équipe jeune et internationale, avec ingénieurs tunisiens","Aucune offre active confirmée; candidature spontanée auprès de l’équipe technique.","Amira Zbidi","https://de.linkedin.com/in/amira-zbidi-443ba2213","Aucun email public vérifié","https://www.linkedin.com/company/shanon-technologies/","https://www.linkedin.com/company/shanon-technologies/ | https://de.linkedin.com/in/amira-zbidi-443ba2213",intl="Oui/partiel — plusieurs profils tunisiens dans l’équipe; contrat et visa non documentés"),
 r("pingme","PingMe — AI4Cure","HealthTech, AI/ML, LLMs, NLP and software engineering","Junior AI/ML Engineer; LLM/NLP Engineer; Python Developer","9.1","73","Un diplômé ENSI 2025 spécialisé ML, NLP et LLM travaille actuellement chez PingMe, ce qui constitue un signal junior et école particulièrement fort.","Oui — diplômé ENSI récent actuellement dans l’équipe","Aucune offre publique active confirmée; approche réseau auprès de l’ancien ENSI recommandée.","Ecil Haoues","https://fr.linkedin.com/in/ecilehaoues","Aucun email public vérifié","https://fr.linkedin.com/in/ecilehaoues","https://fr.linkedin.com/in/ecilehaoues",intl="Oui/partiel — recrutement récent d’un diplômé ENSI tunisien observé"),
 r("m tech","M-TECH","Computer programming","Junior Software Engineer","4.8","15","La société est enregistrée en programmation informatique mais le registre indique zéro salarié et aucune présence de recrutement; le potentiel réel est très faible.","Non — aucune preuve d’embauche et unité non employeuse","Aucune offre active; aucune candidature prioritaire recommandée.","Canal officiel","https://annuaire-entreprises.data.gouv.fr/entreprise/902843366","Aucun email public vérifié","https://annuaire-entreprises.data.gouv.fr/entreprise/902843366","https://annuaire-entreprises.data.gouv.fr/entreprise/902843366",intl="Non — aucun effectif déclaré ni voie de recrutement")
]
OUT.parent.mkdir(parents=True,exist_ok=True); fields=sorted({k for x in RECORDS for k in x})
with OUT.open("w",encoding="utf-8-sig",newline="") as f:
    w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(RECORDS)
print(f"Wrote {len(RECORDS)} records to {OUT}")
