#!/usr/bin/env python3
"""Write the manually verified enrichment records.

Every value here is backed by the URLs stored in ``sources``.  Adding a record
requires checking that the recruiter still works for the organization and that
any job labelled active remains open on the day shown in ``checked_date``.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "job_research" / "verified_research.csv"


RECORDS = [
    {
        "organization_key": "linedata",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Développeur junior, Business Analyst junior, Product Support ou ingénieur IA/Data FinTech",
        "match_score_10": "10.0",
        "match_reason": "Correspondance directe : PFE déjà réalisé chez Linedata, développement logiciel, IA agentique et ingénierie financière.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Offre Développeur Junior – Nouveaux diplômés publiée une semaine avant la vérification ; campagnes récentes Business Analyst et Product Support pour jeunes diplômés.",
        "active_jobs": "Développeur Junior – Nouveaux diplômés — Tunis — https://tn.linkedin.com/jobs/view/4467784719 | Product Support – Nouveaux diplômés — Tunis — https://fr.linkedin.com/company/linedata/jobs | Data Scientist/ML Engineer — Tunis — 2 à 5 ans, moins prioritaire — https://tn.linkedin.com/jobs/view/data-scientist-ml-engineer-at-linedata-4315810459",
        "linkedin_contact_name": "Khaoula Gharbi",
        "linkedin_contact_role": "Professionnelle RH chez Linedata Tunis, auteure de publications de recrutement récentes",
        "linkedin_profile": "https://tn.linkedin.com/in/khaoula-gharbi-",
        "contact_verification": "Profil actuel et publications de recrutement vérifiés",
        "verified_email": "Khaoula.Gharbi@se.linedata.com",
        "email_status": "Adresse publiée récemment par la recruteuse dans une annonce Linedata",
        "application_channel": "https://tn.linkedin.com/jobs/view/4467784719",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "96",
        "sources": "https://tn.linkedin.com/jobs/view/4467784719 | https://fr.linkedin.com/company/linedata/jobs | https://tn.linkedin.com/jobs/view/data-scientist-ml-engineer-at-linedata-4315810459 | https://tn.linkedin.com/in/khaoula-gharbi-",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offre et contact actuels",
        "notes": "Candidature prioritaire. Mettre en avant la connaissance déjà acquise de Linedata et demander si une recommandation interne de l’équipe PFE est possible.",
        "email_subject": "Candidature – Développeur Junior – ancien stagiaire PFE Linedata",
        "email_body": "Bonjour Madame Gharbi,\n\nAprès avoir réalisé mon PFE au sein de Linedata, je souhaite aujourd’hui poursuivre mon parcours dans l’entreprise en candidatant au poste de Développeur Junior – Nouveaux diplômés.\n\nDiplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, j’ai travaillé pendant mon PFE sur la modernisation d’un produit financier à l’aide de trois agents IA, d’une architecture RAG et de 24 outils d’intégration. Cette expérience m’a permis de comprendre les exigences d’un produit FinTech complexe tout en renforçant mes compétences en développement logiciel, Python, Java, C++, bases de données et IA générative.\n\nJe serais très motivé à capitaliser sur cette connaissance de Linedata et à évoluer au sein d’une équipe de développement. Je joins mon CV FinTech et reste disponible pour un entretien.\n\nJe vous remercie pour votre attention.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Gharbi, ancien stagiaire PFE chez Linedata et désormais diplômé de l’ENSI, je candidate au poste de Développeur Junior. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Gharbi, merci d’avoir accepté mon invitation. J’ai réalisé mon PFE chez Linedata sur la modernisation d’un produit financier avec des agents IA et je viens de candidater au poste de Développeur Junior. Puis-je vous transmettre directement mon CV FinTech ?",
    },
    {
        "organization_key": "pwc tunisie",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Data Engineer Junior, ingénieur IA/Data, chef de projet IT junior ou transformation digitale",
        "match_score_10": "9.5",
        "match_reason": "Très forte correspondance avec l’offre Data Engineer Junior, le parcours ENSI, Python, bases de données, IA et la compréhension des métiers financiers.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Offres actuelles Data Engineer Junior et Chef de projet junior ; l’offre Data Engineer prévoit supervision, apprentissage et progression vers l’autonomie.",
        "active_jobs": "Data Engineer Junior — Grand Tunis — https://tn.linkedin.com/jobs/view/4461401221 | Chef de projet junior — Grand Tunis — https://tn.linkedin.com/jobs/view/4437185127 | Ingénieur Workplace — Tunis — https://www.linkedin.com/jobs/view/4456186848/",
        "linkedin_contact_name": "Arbia Triki",
        "linkedin_contact_role": "Senior Talent Acquisition Specialist chez PwC Tunisie",
        "linkedin_profile": "https://tn.linkedin.com/in/arbia-triki",
        "contact_verification": "Profil actuel et publication d’offre PwC vérifiés",
        "verified_email": "FR_TAC_recrutements@pwc.com",
        "email_status": "Adresse de recrutement publiée sur la page LinkedIn officielle de PwC TAC Tunisia",
        "application_channel": "https://tn.linkedin.com/jobs/view/4461401221",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "93",
        "sources": "https://tn.linkedin.com/jobs/view/4461401221 | https://tn.linkedin.com/jobs/view/4437185127 | https://www.linkedin.com/jobs/view/4456186848/ | https://tn.linkedin.com/in/arbia-triki | https://www.linkedin.com/company/pwc-technology-acceleration-center-tunisie",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offres et contact actuels",
        "notes": "Candidature prioritaire au poste Data Engineer Junior. Emna Souli a déjà proposé de transmettre le CV lorsqu’une offre adaptée serait trouvée : lui envoyer également le lien de cette offre.",
        "email_subject": "Candidature – Data Engineer Junior – Ingénieur ENSI",
        "email_body": "Bonjour,\n\nJe vous adresse ma candidature au poste de Data Engineer Junior au sein de PwC.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, j’ai développé une solide base en Python, bases de données, traitement de données, développement logiciel, machine learning et intelligence artificielle. Mon PFE chez Linedata portait sur la modernisation d’un produit financier au moyen d’une solution composée de trois agents IA, d’une architecture RAG et de 24 outils d’intégration.\n\nL’accompagnement structuré, le travail en équipe entre Tunis et Paris et la combinaison entre pipelines de données, BI et besoins métier décrits dans l’offre correspondent précisément à la première expérience que je recherche. Je suis prêt à monter rapidement en compétence sur l’écosystème Microsoft Azure et à contribuer avec rigueur aux développements, à la documentation et au run.\n\nVous trouverez mon CV en pièce jointe. Je reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Triki, diplômé ingénieur ENSI en informatique, je candidate au poste Data Engineer Junior chez PwC. Le rôle correspond à mon parcours Data, IA et ingénierie financière. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Triki, merci d’avoir accepté mon invitation. Je viens de candidater au poste Data Engineer Junior. Mon PFE chez Linedata portait sur la modernisation d’un produit financier avec des agents IA, et je maîtrise Python, les bases de données et le développement logiciel. Puis-je vous transmettre mon CV ?",
    },
    {
        "organization_key": "sofrecom tunisie",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Ingénieur développement logiciel, Full-stack Java, Data/IA junior, DevOps junior ou Business Analyst technique",
        "match_score_10": "8.5",
        "match_reason": "Les activités logiciel, Data/IA, télécom et transformation numérique correspondent au diplôme et aux compétences ; les besoins publics actuels visent toutefois surtout 2 à 5 ans d’expérience.",
        "junior_status": "Oui historiquement ; besoins actuels surtout confirmés",
        "junior_evidence": "Sofrecom propose stages et parcours nouveaux arrivants, et a déjà recruté de jeunes diplômés ; la campagne publique actuelle demande principalement 2 à 5 ans.",
        "active_jobs": "Full Stack Developer — Sofrecom Tunisia — portail officiel : https://www.sofrecom.com/en/jobboard/careers-at-sofrecom.html | Ingénieurs développement mobile iOS/Android — 3 à 5 ans — candidature via https://shorturl.at/8jxlg",
        "linkedin_contact_name": "Boutheina Boussetta",
        "linkedin_contact_role": "Recrutement IT / Talent chez Sofrecom Tunisie",
        "linkedin_profile": "https://tn.linkedin.com/in/boutheina-boussetta-0b407b252",
        "contact_verification": "Profil actuel chez Sofrecom Tunisie et publications d’offres vérifiés",
        "verified_email": "softunisie.rh@sofrecom.com",
        "email_status": "Adresse publiée par la page officielle Sofrecom Tunisie ; publication ancienne, canal officiel actuel à privilégier",
        "application_channel": "https://www.sofrecom.com/en/jobboard/careers-at-sofrecom/candidate.html",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "69",
        "sources": "https://www.sofrecom.com/en/jobboard/careers-at-sofrecom.html | https://www.sofrecom.com/en/jobboard/careers-at-sofrecom/candidate.html | https://tn.linkedin.com/company/sofrecom-tunisie | https://tn.linkedin.com/in/boutheina-boussetta-0b407b252 | https://tn.linkedin.com/posts/sofrecom-tunisie_recrutement-activity-6986265738709741568-0oX5",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — aucune offre junior parfaitement adaptée confirmée",
        "notes": "Candidature spontanée pertinente, mais ne pas présenter les offres senior Data/IA comme accessibles à un débutant.",
        "email_subject": "Candidature spontanée – Ingénieur junior IA, Data et développement logiciel",
        "email_body": "Bonjour Madame Boussetta,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite vous proposer ma candidature pour une première opportunité chez Sofrecom Tunisie en développement logiciel, Data/IA, DevOps junior ou transformation digitale.\n\nMa spécialisation en ingénierie financière complète un profil technique couvrant Python, Java, C++, le développement full-stack, les bases de données, le machine learning et l’IA générative. Lors de mon PFE chez Linedata, j’ai conçu une solution d’IA agentique destinée à moderniser un produit logiciel financier complexe.\n\nJ’ai constaté que plusieurs besoins actuellement publiés s’adressent à des profils plus expérimentés. Je me permets néanmoins de vous contacter pour savoir si une équipe pourrait accueillir un jeune diplômé capable de monter rapidement en compétence et de contribuer à des projets logiciels ou Data/IA.\n\nJe joins mon CV et reste disponible pour échanger.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Boussetta, diplômé ingénieur ENSI en informatique, je recherche une première opportunité en développement, Data ou IA chez Sofrecom Tunisie. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Boussetta, merci d’avoir accepté mon invitation. Je recherche une première opportunité en développement logiciel ou Data/IA. Mon PFE chez Linedata portait sur une solution d’IA agentique. Même si vos besoins actuels semblent plutôt confirmés, puis-je vous transmettre mon CV pour de futurs postes juniors ?",
    },
    {
        "organization_key": "wevioo",
        "sector": "IA / Data / Logiciel",
        "target_roles": "AI/Data Engineer junior, développeur logiciel, consultant Data/IA junior ou Business Analyst technique",
        "match_score_10": "8.5",
        "match_reason": "Wevioo travaille en transformation digitale, Data/IA, logiciel et secteurs financiers ; les offres techniques actuelles sont principalement confirmées.",
        "junior_status": "Oui — CIVP et recrutements juniors observés",
        "junior_evidence": "Le portail actuel comporte un poste Product Owner en CIVP ; Wevioo a régulièrement publié des postes juniors et des PFE, mais le poste Data Science/AI actuel est confirmé.",
        "active_jobs": "Product Owner — Tunis — CIVP — https://wevioo.com/en/job-offers/ | Confirmed Data Science/AI Engineer — Tunis — CDI — https://wevioo.com/en/job-offers/ | Management Consultant — Tunis — CDI — https://wevioo.com/en/job-offers/",
        "linkedin_contact_name": "Myriam Bouchahoua",
        "linkedin_contact_role": "Psychologue du travail et chargée de recrutement chez Wevioo",
        "linkedin_profile": "https://tn.linkedin.com/in/myriambouchahoua",
        "contact_verification": "Profil actuel et publications de recrutement Wevioo vérifiés",
        "verified_email": "myriam.bouchahoua@wevioo.com",
        "email_status": "Adresse publiée par la recruteuse dans une annonce Wevioo ; contact@wevioo.com est également publié sur le portail officiel",
        "application_channel": "https://wevioo.com/offres-demploi/2/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "74",
        "sources": "https://wevioo.com/offres-demploi/2/ | https://wevioo.com/en/job-offers/ | https://tn.linkedin.com/in/myriambouchahoua | https://fr.linkedin.com/posts/myriambouchahoua_product-owner-activity-7401933550935060480-C3EE",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — portail actif, pas de poste IA junior exact",
        "notes": "Envoyer une candidature spontanée ciblée junior et surveiller le portail ; ne pas candidater au poste Confirmed Data Science/AI Engineer comme s’il était junior.",
        "email_subject": "Candidature junior – Intelligence artificielle, Data et développement logiciel",
        "email_body": "Bonjour Madame Bouchahoua,\n\nJe souhaite vous proposer ma candidature pour une première opportunité chez Wevioo autour de l’intelligence artificielle, de la Data, du développement logiciel ou du conseil technologique.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je maîtrise Python, Java, C++, le développement full-stack, les bases de données, le machine learning et l’IA générative. Mon PFE chez Linedata portait sur la modernisation d’un produit financier à l’aide d’une solution composée de plusieurs agents IA.\n\nLes activités de Wevioo en Data Analytics, IA et transformation digitale, notamment dans les secteurs bancaire et assurantiel, correspondent particulièrement à mon parcours. J’ai vu que le besoin Data Science/AI actuellement publié recherche un profil confirmé ; je vous contacte donc pour savoir si une opportunité junior ou un besoin à venir pourrait correspondre à mon profil.\n\nJe joins mon CV et serais ravi d’échanger avec vous.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Bouchahoua, jeune ingénieur ENSI spécialisé en informatique, IA et ingénierie financière, je m’intéresse aux opportunités juniors chez Wevioo. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Bouchahoua, merci d’avoir accepté mon invitation. Mon PFE chez Linedata portait sur une solution d’IA agentique appliquée à un produit financier. Je recherche une première opportunité en IA, Data, logiciel ou conseil. Puis-je vous transmettre mon CV pour vos besoins juniors actuels ou futurs ?",
    },
    {
        "organization_key": "vneuron",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Ingénieur Solutions Junior, Support & Integration Engineer, consultant technico-fonctionnel ou ingénieur logiciel RegTech",
        "match_score_10": "9.5",
        "match_reason": "Excellente correspondance entre informatique, ingénierie financière, intégration, Data/IA et les produits RegTech de lutte contre la criminalité financière.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Le portail carrière affiche actuellement Ingénieur Solutions Junior – TBML et plusieurs rôles techniques à Tunis ; Vneuron a aussi recruté explicitement des jeunes diplômés.",
        "active_jobs": "Ingénieur Solutions Junior – TBML — Tunis — https://vneuron-group.careers-page.com/jobs/7809f561-1d41-4713-ba33-830416cc95c3 | Support & Integration Engineer — Tunis — https://vneuron-group.careers-page.com/",
        "linkedin_contact_name": "Fatma Aloulou",
        "linkedin_contact_role": "Recruteuse spécialisée Tech chez Vneuron Risk & Compliance",
        "linkedin_profile": "https://fr.linkedin.com/in/fatma-aloulou",
        "contact_verification": "Profil actuel Vneuron et publications de recrutement vérifiés",
        "verified_email": "Aucun email public de recrutement vérifié",
        "email_status": "Utiliser le portail carrière ; hello@vneuron.com est un contact commercial et n’est pas retenu pour une candidature",
        "application_channel": "https://vneuron-group.careers-page.com/jobs/7809f561-1d41-4713-ba33-830416cc95c3",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "94",
        "sources": "https://vneuron-group.careers-page.com/jobs/7809f561-1d41-4713-ba33-830416cc95c3 | https://vneuron-group.careers-page.com/ | https://fr.linkedin.com/in/fatma-aloulou | https://www.linkedin.com/posts/fatma-aloulou_vneuron-hiring-recrutement-activity-7188945261514153984-niLH",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offre junior et contact actuels",
        "notes": "Candidature très prioritaire à Ingénieur Solutions Junior – TBML. Utiliser le portail, puis contacter Fatma Aloulou sur LinkedIn.",
        "email_subject": "Candidature – Ingénieur Solutions Junior TBML – Ingénieur ENSI",
        "email_body": "Bonjour Madame Aloulou,\n\nJe souhaite candidater au poste d’Ingénieur Solutions Junior – TBML chez Vneuron.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, mon profil relie développement logiciel, intégration, données et compréhension des enjeux financiers. Lors de mon PFE chez Linedata, j’ai participé à la modernisation d’un produit financier en concevant une solution composée de trois agents IA, d’une architecture RAG et de 24 outils d’intégration.\n\nLes missions de préparation des environnements, intégration des données, tests, mise en production et accompagnement des utilisateurs correspondent à mon approche : comprendre le besoin métier puis construire une solution fiable et exploitable. Je maîtrise notamment Python, Java, C++, les bases de données et le développement full-stack.\n\nJe joins mon CV FinTech et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Aloulou, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je candidate au poste Ingénieur Solutions Junior chez Vneuron. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Aloulou, merci d’avoir accepté mon invitation. Je viens de candidater au poste Ingénieur Solutions Junior – TBML. Mon PFE chez Linedata combinait produit financier, intégration et agents IA. Puis-je vous transmettre directement mon CV FinTech ?",
    },
    {
        "organization_key": "axe finance",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Junior Business Consultant, Business Analyst junior, QA junior, ingénieur intégration ou IA/Data appliquée au crédit",
        "match_score_10": "9.5",
        "match_reason": "Très forte adéquation FinTech : logiciel de crédit, automatisation, IA, banques et combinaison informatique/finance.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Publications récentes Junior Finance Specialist, Junior QA Consultants, stages R&D et catalogue PFE 2026 ; parcours d’intégration de jeunes talents.",
        "active_jobs": "Cloud Administrator — Tunis — https://www.axefinance.com/company/careers/ | Finance Specialist — Tunis — https://www.axefinance.com/company/careers/ | UX/UI Designer — Tunis — https://www.axefinance.com/company/careers/",
        "linkedin_contact_name": "Zeineb Kassis",
        "linkedin_contact_role": "Talent Acquisition & HR Specialist chez Axe Finance",
        "linkedin_profile": "https://tn.linkedin.com/in/zeineb-kassis-27549a182",
        "contact_verification": "Profil actuel et publications de recrutement récentes vérifiés",
        "verified_email": "hr@axefinance.com",
        "email_status": "Adresse publiée dans des documents de recrutement Axe Finance récents",
        "application_channel": "https://www.axefinance.com/company/careers/",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "86",
        "sources": "https://www.axefinance.com/company/careers/ | https://tn.linkedin.com/in/zeineb-kassis-27549a182 | https://tunis-business-school.tn/uploads/2024/Axefinance%20Opportunities.pdf | https://www.manocasa.tn/uploads/1763475333_Axe_Finance.pdf",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — entreprise junior-friendly, aucun poste technique junior exact actuellement confirmé",
        "notes": "Envoyer une candidature spontanée ciblée FinTech. Les postes actuellement visibles ne sont pas tous adaptés, mais la société recrute régulièrement des juniors.",
        "email_subject": "Candidature junior – FinTech, IA et développement logiciel",
        "email_body": "Bonjour Madame Kassis,\n\nJe souhaite vous proposer ma candidature pour une première opportunité chez Axe Finance en tant que Business Analyst junior, consultant logiciel, ingénieur intégration, QA junior ou sur un sujet Data/IA appliqué au crédit.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, j’ai réalisé mon PFE chez Linedata sur la modernisation d’un produit financier à l’aide de trois agents IA, d’une architecture RAG et de 24 outils d’intégration. Je maîtrise également Python, Java, C++, le développement full-stack et les bases de données.\n\nL’activité d’Axe Finance, à l’intersection du logiciel, de l’automatisation du crédit et des métiers bancaires, correspond directement au type d’environnement dans lequel je souhaite construire mon début de carrière.\n\nJe joins mon CV FinTech et reste ouvert à tout poste junior cohérent avec mon diplôme.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Kassis, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je m’intéresse aux opportunités juniors FinTech chez Axe Finance. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Kassis, merci d’avoir accepté mon invitation. Mon PFE chez Linedata portait sur la modernisation d’un produit financier avec des agents IA. Je recherche un poste junior en Business Analysis, logiciel, QA, intégration ou Data/IA. Puis-je vous transmettre mon CV FinTech ?",
    },
    {
        "organization_key": "talan tunisie",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Développeur logiciel junior, consultant CRM junior, Data/AI Engineer junior ou consultant technique",
        "match_score_10": "8.5",
        "match_reason": "Bonne adéquation en développement, Data/IA et conseil ; l’offre junior actuelle demande toutefois une première exposition à Dynamics 365 CRM.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Offre Consultant CRM Junior publiée récemment, programme SummerCamp 2026 et campagnes régulières pour jeunes talents.",
        "active_jobs": "Consultant CRM Junior – Microsoft Dynamics 365 CE — Tunis — https://www.linkedin.com/company/talan-tunisie | Consultant Full Stack Java/Angular — Tunis — contacter Henda Hajouni",
        "linkedin_contact_name": "Henda Hajouni",
        "linkedin_contact_role": "Recrutement chez Talan Tunisie",
        "linkedin_profile": "https://tn.linkedin.com/in/henda-hajouni-b22401130",
        "contact_verification": "Profil Talan actuel et publication de recrutement de moins d’une semaine vérifiés",
        "verified_email": "henda.hajjouni@talan.com",
        "email_status": "Adresse publiée dans des annonces Talan actuelles",
        "application_channel": "https://www.linkedin.com/company/talan-tunisie",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "82",
        "sources": "https://www.linkedin.com/company/talan-tunisie | https://tn.linkedin.com/in/henda-hajouni-b22401130 | https://fr.linkedin.com/posts/henda-hajouni-b22401130_consultant-full-stack-javaangular-activity-7505549012188438528-Y9C6 | https://www.talan.com/global/fr/carrieres/notre-processus-de-recrutement",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — recrutements juniors et techniques actuels",
        "notes": "Candidater au Full Stack Java/Angular si l’annonce accepte les débutants ; pour CRM Junior, reconnaître l’absence d’expérience Dynamics 365 et valoriser la capacité d’apprentissage.",
        "email_subject": "Candidature junior – Développement logiciel, Data et IA",
        "email_body": "Bonjour Madame Hajouni,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite vous proposer ma candidature pour une première opportunité chez Talan Tunisie en développement logiciel, Data/IA ou conseil technique.\n\nJe maîtrise Python, Java, C++, le développement full-stack, les bases de données, le machine learning et l’IA générative. Lors de mon PFE chez Linedata, j’ai développé une solution d’IA agentique destinée à moderniser un produit logiciel financier complexe. J’ai également dirigé une équipe de développement dans le cadre de mes responsabilités de CTO chez S&S Advisory.\n\nLes projets de Talan autour de la Data, de l’IA et de la transformation numérique correspondent à mon projet professionnel. Je suis prêt à monter rapidement en compétence sur les technologies propres aux missions, notamment l’écosystème Microsoft lorsque cela est nécessaire.\n\nJe joins mon CV et reste disponible pour échanger sur vos postes juniors actuels ou futurs.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Hajouni, ingénieur ENSI récemment diplômé, je recherche une première opportunité en développement, Data ou IA chez Talan Tunisie. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Hajouni, merci d’avoir accepté mon invitation. Je maîtrise Python, Java, C++, le full-stack et l’IA générative ; mon PFE chez Linedata portait sur des agents IA. Je m’intéresse à vos besoins juniors et Full Stack. Puis-je vous transmettre mon CV ?",
    },
    {
        "organization_key": "vermeg",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Software Developer junior Java/JEE, Business Analyst junior, QA Analyst ou ingénieur IA/Data FinTech",
        "match_score_10": "9.5",
        "match_reason": "Très forte adéquation entre logiciel financier, Java, ingénierie financière, Business Analysis et expérience PFE FinTech.",
        "junior_status": "Oui historiquement ; talent community active",
        "junior_evidence": "Vermeg a recruté des Software Developers juniors et mène des programmes Academy/alternance ; aucune offre junior tunisienne exacte n’a été confirmée le jour de la vérification.",
        "active_jobs": "Aucune offre junior tunisienne vérifiée ; rejoindre la Talent Community : https://www.vermeg.com/careers/ | DBA & Cloud Systems Lead — Tunis — poste senior non adapté",
        "linkedin_contact_name": "Chiraz Fellah",
        "linkedin_contact_role": "Talent Acquisition Specialist chez Vermeg",
        "linkedin_profile": "https://tn.linkedin.com/in/chiraz-fellah-8678ab33",
        "contact_verification": "Profil actuel Vermeg et publication de recrutement vérifiés",
        "verified_email": "job@vermeg.com",
        "email_status": "Adresse publiée dans les annonces Vermeg, y compris par la Talent Acquisition Specialist",
        "application_channel": "https://www.vermeg.com/careers/",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "78",
        "sources": "https://www.vermeg.com/careers/ | https://www.vermeg.com/contact-us/ | https://tn.linkedin.com/in/chiraz-fellah-8678ab33 | https://fr.linkedin.com/posts/chiraz-fellah-8678ab33_pour-renforcer-nos-%C3%A9quipes-vermeg-tunis-recrute-activity-6391539013110558720-EowN",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — canal actif, pas d’offre junior tunisienne exacte confirmée",
        "notes": "Candidature spontanée prioritaire avec CV FinTech ; ne pas utiliser l’ancienne annonce Junior Java comme si elle était ouverte.",
        "email_subject": "Candidature junior – Software Engineering et FinTech",
        "email_body": "Bonjour Madame Fellah,\n\nJe souhaite vous proposer ma candidature pour une première opportunité chez Vermeg en développement logiciel, Business Analysis, QA ou Data/IA appliquée aux services financiers.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je maîtrise notamment Java, Python, C++, le développement full-stack et les bases de données. Mon PFE chez Linedata portait sur la modernisation d’un produit financier au moyen de trois agents IA, d’une architecture RAG et de 24 outils d’intégration.\n\nLe positionnement de Vermeg dans les logiciels bancaires, les marchés de capitaux et l’assurance correspond directement à mon double profil informatique et finance. Je serais heureux d’être considéré pour tout poste junior adapté, actuellement ou à venir.\n\nJe joins mon CV FinTech et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour Mme Fellah, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je m’intéresse aux opportunités juniors chez Vermeg. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Fellah, merci d’avoir accepté mon invitation. Mon PFE chez Linedata associait développement logiciel, finance et agents IA. Je recherche un poste junior en développement, Business Analysis, QA ou Data/IA. Puis-je vous transmettre mon CV FinTech ?",
    },
    {
        "organization_key": "telnet",
        "sector": "Télécom / Électronique / Industrie",
        "target_roles": "Ingénieur logiciel C/C++ junior, ingénieur validation, développeur embarqué junior ou ingénieur IA appliquée",
        "match_score_10": "8.5",
        "match_reason": "Très bonne adéquation avec C/C++, Python, développement logiciel et IA ; le profil possède moins d'expérience pratique en systèmes embarqués et protocoles matériels.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Une campagne récente à Tunis recherchait deux ingénieurs Validation Systèmes Embarqués avec 0 à 2 ans d'expérience ; TELNET maintient aussi un vivier de stagiaires PFE et jeunes talents.",
        "active_jobs": "Aucune offre junior encore confirmée ouverte le 24/09/2026 ; campagne récente Ingénieur Validation Systèmes Embarqués (0–2 ans) — Tunis — contacter Rihab Braïek",
        "linkedin_contact_name": "Rihab Braïek",
        "linkedin_contact_role": "Talent Acquisition / recrutement chez TELNET Tunisie",
        "linkedin_profile": "https://tn.linkedin.com/in/rihabbra%C3%AFek",
        "contact_verification": "Profil TELNET actuel et publications de recrutement des six derniers mois vérifiés",
        "verified_email": "rihab.braiek@groupe-telnet.net",
        "email_status": "Adresse publiée récemment par la recruteuse dans plusieurs campagnes TELNET",
        "application_channel": "mailto:rihab.braiek@groupe-telnet.net",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "80",
        "sources": "https://tn.linkedin.com/in/rihabbra%C3%AFek | https://tn.linkedin.com/in/telnet-tunisie-bb5883140 | https://www.linkedin.com/posts/telnet-tunisie-bb5883140_wearetelnet-worktogether-growtogether-activity-7042536833007661056-coWI",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — junior-friendly, aucune offre exacte encore confirmée ouverte",
        "notes": "Candidature spontanée ciblée. Ne pas présenter la campagne 0–2 ans vieille de six mois comme une offre active ; demander l'existence d'un besoin actuel en logiciel, validation ou IA.",
        "email_subject": "Candidature junior — Ingénierie logicielle C/C++, Python et IA",
        "email_body": "Bonjour Madame Braïek,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite vous proposer ma candidature pour une première opportunité chez TELNET en développement logiciel, validation ou intelligence artificielle appliquée.\n\nJe maîtrise C++, Python, Java, le développement full-stack, les bases de données et l’IA générative. Mon PFE chez Linedata portait sur la modernisation d’un produit logiciel financier au moyen d’agents IA, tandis que mes autres projets m’ont appris à concevoir, tester et documenter des solutions complètes.\n\nLes projets de TELNET dans les systèmes embarqués, les télécommunications et l’innovation technologique m’intéressent particulièrement. Même si mon expérience embarquée est encore à consolider, mes bases en C/C++, mon esprit d’analyse et ma capacité d’apprentissage me permettraient de progresser rapidement sur vos outils et protocoles.\n\nJe joins mon CV et reste disponible pour tout poste junior correspondant à mon diplôme.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Braïek, ingénieur ENSI récemment diplômé, je m’intéresse aux opportunités juniors en logiciel, validation et IA chez TELNET. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Braïek, merci d’avoir accepté mon invitation. Je maîtrise C++, Python, Java et l’IA ; mon PFE chez Linedata portait sur des agents IA. J’ai vu que TELNET recrutait des ingénieurs juniors en validation. Puis-je vous transmettre mon CV pour vos besoins actuels ou futurs ?",
    },
    {
        "organization_key": "fis",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "C++ Software Engineer junior, Software Engineer FinTech, Business Analyst junior ou ingénieur IA/Data",
        "match_score_10": "9.0",
        "match_reason": "Excellente cohérence entre C++, développement logiciel, finance de marché, IA et PFE FinTech ; l'offre C++ actuelle est toutefois annoncée au niveau expérimenté.",
        "junior_status": "Oui — historique confirmé ; offre actuelle expérimentée",
        "junior_evidence": "FIS dispose d'un University Program ayant accueilli des étudiants ENSI et a déjà recruté des C++ Software Engineer I ; l'offre C++ active actuelle est classée Mid-Senior/Experienced.",
        "active_jobs": "C++ Software Engineer — Ariana — https://www.linkedin.com/jobs/view/4456483733/ — active mais niveau Experienced/Mid-Senior, candidature possible sans la présenter comme junior",
        "linkedin_contact_name": "Ramla Bejaoui",
        "linkedin_contact_role": "Talent Acquisition Business Partner Sr Lead chez FIS, recruteuse de l'offre C++ à Ariana",
        "linkedin_profile": "https://www.linkedin.com/in/ramla-bejaoui",
        "contact_verification": "Nom, fonction et rattachement FIS confirmés directement sur l'offre active",
        "verified_email": "Aucun email public vérifié",
        "email_status": "Aucune adresse publique actuelle vérifiée ; utiliser le bouton Apply de l'offre ou le portail FIS",
        "application_channel": "https://www.linkedin.com/jobs/view/4456483733/",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "77",
        "sources": "https://www.linkedin.com/jobs/view/4456483733/ | https://careers.fisglobal.com/us/en/fis-tunisia | https://www.linkedin.com/in/julie-forse-mba",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offre active et recruteuse actuelle, niveau d'expérience défavorable",
        "notes": "Postuler via le portail en assumant clairement le statut junior. Mettre en avant C++, la finance et la capacité d'apprentissage ; ne pas envoyer d'email inventé.",
        "email_subject": "Application — C++ Software Engineer — ENSI Computer Engineer",
        "email_body": "Dear Ms. Bejaoui,\n\nI am applying for the C++ Software Engineer position at FIS in Ariana. I recently graduated as a Computer Engineer from ENSI, with a specialization in Financial Engineering, and I am looking to begin my career in an environment where software engineering directly supports financial markets.\n\nI have a strong foundation in C++, Python, Java, object-oriented development, databases and software testing. During my final-year project at Linedata, I helped modernize a complex financial product through an agentic AI solution, which strengthened both my software engineering discipline and my understanding of FinTech products.\n\nI recognize that the current vacancy is presented as an experienced position. While I am at the beginning of my career, I believe my technical foundation, financial specialization and ability to learn quickly make my profile worth considering for this role or for an upcoming entry-level opportunity within the team.\n\nPlease find my FinTech CV attached. I would be pleased to discuss how I could contribute and grow at FIS.\n\nKind regards,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Bejaoui, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je m’intéresse au poste C++ chez FIS Ariana et à vos opportunités juniors. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Bejaoui, merci d’avoir accepté mon invitation. J’ai candidaté au poste C++ à Ariana. Je suis junior, mais mon profil associe C++, logiciel, ingénierie financière et un PFE IA chez Linedata. Je serais également intéressé par toute ouverture entry-level adaptée. Puis-je vous transmettre mon CV FinTech ?",
    },
    {
        "organization_key": "sopra hr software tunisie",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Développeur logiciel junior, consultant exploitation junior, intégrateur applicatif, Data/IA ou ingénieur cloud junior",
        "match_score_10": "8.0",
        "match_reason": "Bonne base en développement, bases de données, IA et transformation digitale ; les offres techniques actuelles visibles demandent principalement 3 à 5 ans d'expérience.",
        "junior_status": "Oui historiquement ; non confirmé sur une offre actuelle adaptée",
        "junior_evidence": "Sopra HR a déjà recruté des consultants exploitation et intégrateurs junior ; le portail actuel affiche surtout des postes techniques avec 3 à 5 ans d'expérience.",
        "active_jobs": "Aucune offre junior technique adaptée confirmée ; offres actuelles 3–5 ans sur https://careers.soprasteria.com/ — ne pas utiliser les anciennes annonces junior fermées",
        "linkedin_contact_name": "Selima Daly",
        "linkedin_contact_role": "HR Business Partner / Responsable recrutement chez Sopra HR Software",
        "linkedin_profile": "https://tn.linkedin.com/in/selima-daly-b15b7913a",
        "contact_verification": "Profil actuel et activité récente chez Sopra HR vérifiés",
        "verified_email": "selima.daly@soprahr.com",
        "email_status": "Adresse publiée par la responsable recrutement dans ses campagnes Sopra HR",
        "application_channel": "https://careers.soprasteria.com/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "65",
        "sources": "https://tn.linkedin.com/in/selima-daly-b15b7913a | https://careers.soprasteria.com/job/developpeur-consultant-hr-access-hra-in-tunis-tunisia-jid-9262 | https://careers.soprasteria.com/job/ingenieur-identity-and-access-management-in-tunis-tunisia-jid-6098",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — contact actuel, aucune offre junior technique exacte confirmée",
        "notes": "Candidature spontanée à envoyer à Selima Daly. Les anciennes offres Consultant exploitation junior et Intégrateur junior sont des preuves d'ouverture historique, pas des offres actives.",
        "email_subject": "Candidature junior — Développement logiciel, Data et IA",
        "email_body": "Bonjour Madame Daly,\n\nJe souhaite vous proposer ma candidature pour une première opportunité chez Sopra HR Software en développement logiciel, intégration applicative, exploitation, Data ou intelligence artificielle.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je maîtrise Python, Java, C++, le développement full-stack, les bases de données, le machine learning et l’IA générative. Mon PFE chez Linedata portait sur la modernisation d’un produit financier complexe grâce à une solution d’IA agentique, de sa conception jusqu’à son intégration et sa validation.\n\nL’environnement produit de Sopra HR, au croisement du logiciel, du cloud et de la transformation digitale des métiers RH, correspond au cadre dans lequel je souhaite construire mon début de carrière. Je suis prêt à me former rapidement aux produits et technologies spécifiques de vos équipes.\n\nJe joins mon CV et serais reconnaissant si mon profil pouvait être considéré pour tout besoin junior actuel ou à venir.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Daly, ingénieur ENSI récemment diplômé, je recherche une première opportunité en développement, intégration, Data ou IA chez Sopra HR. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Daly, merci d’avoir accepté mon invitation. Mon profil combine Python, Java, C++, full-stack, bases de données et IA, avec un PFE chez Linedata. Je reste ouvert aux métiers techniques liés à mon diplôme. Puis-je vous transmettre mon CV pour vos besoins juniors ?",
    },
    {
        "organization_key": "bh bank",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Auditeur informatique junior, ingénieur IT, Data/IA, cybersécurité, risques technologiques ou transformation digitale",
        "match_score_10": "8.5",
        "match_reason": "Double profil informatique et ingénierie financière pertinent pour l'audit IT, les systèmes d'information, la Data/IA et la modernisation bancaire.",
        "junior_status": "Oui — processus officiel et concours historiques ; besoin actuel non vérifié",
        "junior_evidence": "Le portail officiel accepte les candidatures spontanées et décrit un processus de sélection ; le concours 2024 incluait des cadres en informatique et audit, mais il est clos.",
        "active_jobs": "Aucune offre informatique junior active confirmée ; candidature spontanée via https://www.bhbank.tn/carrieres",
        "linkedin_contact_name": "Lamia Tlili",
        "linkedin_contact_role": "Direction centrale du Capital humain chez BH Bank",
        "linkedin_profile": "https://tn.linkedin.com/in/lamia-tlili-8981a3115",
        "contact_verification": "Profil actuel rattaché à BH Bank ; l'intitulé exact de direction provient des informations institutionnelles disponibles",
        "verified_email": "Aucun email public vérifié",
        "email_status": "L'adresse précédemment testée n'est pas utilisée ; candidature uniquement par le formulaire officiel",
        "application_channel": "https://www.bhbank.tn/carrieres",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "69",
        "sources": "https://www.bhbank.tn/carrieres | https://tn.linkedin.com/in/lamia-tlili-8981a3115 | https://recrutement.bhbank.tn/AvisConcours072024-FR.pdf",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — canal officiel actif, aucune offre IT junior actuelle confirmée",
        "notes": "Dans le formulaire, indiquer comme objectif prioritaire Auditeur informatique, tout en restant ouvert aux métiers IT, IA, Data, cybersécurité et transformation digitale compatibles avec le diplôme.",
        "email_subject": "Candidature spontanée — Auditeur informatique / Ingénieur IT junior",
        "email_body": "Bonjour Madame, Monsieur,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je souhaite rejoindre BH Bank en priorité comme auditeur informatique, tout en restant ouvert à tout métier lié aux systèmes d’information, à la Data, à l’intelligence artificielle, à la cybersécurité ou à la transformation digitale.\n\nMon PFE chez Linedata portait sur la modernisation d’un produit financier à l’aide d’agents IA. Cette expérience m’a permis de relier les enjeux technologiques aux exigences de fiabilité, de contrôle et d’efficacité propres au secteur financier. Je maîtrise également Python, Java, C++, le développement full-stack et les bases de données.\n\nJe souhaite mettre ce double regard informatique et financier au service de la modernisation, de la maîtrise des risques technologiques et de l’amélioration des processus de BH Bank.\n\nJe joins mon CV FinTech et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Tlili, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je m’intéresse aux métiers d’audit IT, Data/IA et transformation digitale chez BH Bank. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Tlili, merci d’avoir accepté mon invitation. J’ai déposé une candidature spontanée auprès de BH Bank. Je vise en priorité l’audit informatique, tout en restant ouvert aux métiers IT, IA, Data et cybersécurité liés à mon diplôme. Puis-je vous transmettre mon CV FinTech ?",
    },
    {
        "organization_key": "biat innovation technology",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Business Analyst junior, QA Engineer junior, Software Engineer, Data/AI Engineer ou transformation digitale bancaire",
        "match_score_10": "9.5",
        "match_reason": "Correspondance directe avec le double profil logiciel-finance, le PFE FinTech, l'IA agentique et les besoins BIAT IT en Business Analysis, QA et transformation digitale.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "BIAT IT a publié des postes Junior Business Analyst et QA Engineer avec moins d'un an d'expérience, et communique activement sur le démarrage de carrière en IT.",
        "active_jobs": "Aucune offre junior nommément confirmée ouverte le 24/09/2026 ; appel récent à rejoindre BIAT IT et canal Hiring@biat-it.com.tn actifs — candidature spontanée ciblée",
        "linkedin_contact_name": "Salma Khabthani",
        "linkedin_contact_role": "HR Leader chez BIAT Innovation & Technology",
        "linkedin_profile": "https://tn.linkedin.com/in/salma-khabthani-405481143",
        "contact_verification": "Profil actuel BIAT IT et publications de recrutement vérifiés",
        "verified_email": "Hiring@biat-it.com.tn",
        "email_status": "Adresse publiée à plusieurs reprises sur la page officielle et par la HR Leader, y compris dans les communications récentes",
        "application_channel": "mailto:Hiring@biat-it.com.tn",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "88",
        "sources": "https://www.linkedin.com/company/biat-innovation-technology | https://tn.linkedin.com/in/salma-khabthani-405481143 | https://www.linkedin.com/posts/salma-khabthani-405481143_ready-to-shape-the-future-join-biat-innovation-activity-7415402085829009408-bbfV | https://www.linkedin.com/posts/biat-innovation-technology_open-positions-qa-digital-qa-business-activity-7453120488068857857-kA-6",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — junior-friendly et canal actuel, aucune offre exacte encore confirmée ouverte",
        "notes": "Envoyer une candidature spontanée orientée Business Analysis, QA et Data/IA bancaire ; ne pas présenter les publications de cinq à sept mois comme des offres encore ouvertes.",
        "email_subject": "Candidature junior — Business Analysis, QA et Data/IA bancaire",
        "email_body": "Bonjour Madame Khabthani,\n\nJe souhaite vous proposer ma candidature pour une première opportunité au sein de BIAT Innovation & Technology, en Business Analysis, QA, développement logiciel ou Data/IA appliquée aux services bancaires.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, j’ai réalisé mon PFE chez Linedata sur la modernisation d’un produit financier à l’aide d’agents IA. Ce projet m’a appris à comprendre un besoin métier, structurer une solution, collaborer avec des équipes produit et garantir la qualité de l’intégration. Je maîtrise également Python, Java, C++, le développement full-stack et les bases de données.\n\nLa mission de BIAT IT, qui consiste à transformer l’expérience bancaire par la technologie, correspond exactement à mon projet professionnel. Je souhaite apporter mon double regard informatique et financier tout en progressant dans un environnement qui valorise la curiosité et l’apprentissage continu.\n\nJe joins mon CV FinTech et reste disponible pour échanger sur vos besoins juniors actuels ou futurs.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Khabthani, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je m’intéresse aux opportunités juniors BA, QA et Data/IA chez BIAT IT. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Khabthani, merci d’avoir accepté mon invitation. Je viens d’envoyer ma candidature à Hiring@biat-it.com.tn. Mon PFE chez Linedata associait logiciel financier et agents IA. Je reste ouvert aux rôles junior BA, QA, développement ou Data/IA. Puis-je aussi vous transmettre mon CV FinTech ici ?",
    },
    {
        "organization_key": "uib",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Ingénieur études et développements, ingénieur systèmes, réseaux et sécurité, Data/IA ou maîtrise d'ouvrage junior",
        "match_score_10": "9.5",
        "match_reason": "L'offre Ingénieur Études et Développements vise explicitement un jeune diplômé et correspond aux compétences Java, web, SQL, génie logiciel et ingénierie financière.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Le site officiel présente actuellement Ingénieur Études et Développements et Ingénieur Réseaux et Sécurité comme des postes pour jeunes diplômés.",
        "active_jobs": "Ingénieur Études et Développements — Tunis — https://www.uib.com.tn/carriere/nos-offres | Ingénieur Réseaux et Sécurité — Tunis — même page | Ingénieur Sécurité SOC — Tunis — 3 à 5 ans, non prioritaire",
        "linkedin_contact_name": "Sarah Bayoudhi",
        "linkedin_contact_role": "Professionnelle RH/recrutement chez UIB, interlocutrice de campagnes de recrutement",
        "linkedin_profile": "https://www.linkedin.com/in/sarah-bayoudhi-aa9b2618a/",
        "contact_verification": "Activité de recrutement UIB vérifiée ; rattachement actuel à confirmer visuellement avant l'envoi de l'invitation",
        "verified_email": "recrutement@uib.com.tn",
        "email_status": "Adresse publiée récemment par des collaborateurs UIB et utilisée dans les campagnes officielles",
        "application_channel": "https://recrutement.uib.com.tn/",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "95",
        "sources": "https://www.uib.com.tn/carriere/nos-offres | https://recrutement.uib.com.tn/ | https://tn.linkedin.com/in/asma-karoui-929263159 | https://www.linkedin.com/posts/sarah-bayoudhi-aa9b2618a_lunion-internationale-de-banques-groupe-activity-6969992610920697856-43cY",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offres juniors et email actuels",
        "notes": "Candidature immédiate à Ingénieur Études et Développements. Vérifier sur le profil LinkedIn que Sarah Bayoudhi est toujours liée à UIB avant invitation ; sinon contacter Asma Karoui, qui partage les offres actuelles.",
        "email_subject": "Candidature — Ingénieur Études et Développements — Jeune diplômé ENSI",
        "email_body": "Bonjour Madame, Monsieur,\n\nJe vous adresse ma candidature au poste d’Ingénieur Études et Développements au sein de l’UIB.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je dispose des compétences attendues en génie logiciel, Java, développement web, bases de données et SQL. Mon PFE chez Linedata portait sur la modernisation d’un produit financier au moyen d’agents IA, de sa conception jusqu’aux tests et à l’intégration.\n\nCe poste m’intéresse particulièrement parce qu’il associe analyse, conception, développement, mise en production et support au sein d’un environnement bancaire. Mon parcours me permet de comprendre à la fois les contraintes techniques et les enjeux métier, tout en restant très ouvert à l’apprentissage des technologies et processus propres à l’UIB.\n\nJe joins mon CV FinTech et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Bayoudhi, ingénieur ENSI récemment diplômé en informatique et ingénierie financière, je candidate au poste Ingénieur Études et Développements de l’UIB. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Bayoudhi, merci d’avoir accepté mon invitation. Je viens de candidater au poste Ingénieur Études et Développements. Mon profil associe Java, web, SQL, IA et ingénierie financière, avec un PFE chez Linedata. Puis-je vous transmettre directement mon CV FinTech ?",
    },
    {
        "organization_key": "focus",
        "sector": "IA / Data / Logiciel",
        "target_roles": "ERP Development Engineer, SAP BTP Technical Support Engineer, Software Engineer junior C/C++ ou QA/AI Engineer",
        "match_score_10": "9.0",
        "match_reason": "Très forte adéquation avec le diplôme d'ingénieur, SQL, Linux, C/C++, Python, développement logiciel et capacité à apprendre de nouveaux environnements.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "Deux offres Entry level publiées depuis quelques jours invitent explicitement les ingénieurs diplômés à démarrer dans les écosystèmes ERP et SAP BTP.",
        "active_jobs": "ERP Development Engineer — Tunis — https://www.linkedin.com/jobs/view/4454710516/ | SAP BTP Technical Support Engineer — Tunis — https://www.linkedin.com/jobs/view/4448289528/ | ABAP/Fiori/SAPUI5 Developer — Tunis — https://www.linkedin.com/jobs/view/4450095019/ — 3 ans, non prioritaire",
        "linkedin_contact_name": "Rawen Hadded",
        "linkedin_contact_role": "Talent Acquisition Specialist / IT Recruiter chez Focus Corporation, auteure des offres actives",
        "linkedin_profile": "Profil direct non trouvé ; ouvrir le profil Rawen Hadded depuis https://www.linkedin.com/jobs/view/4454710516/",
        "contact_verification": "Fonction et rattachement Focus confirmés sur plusieurs offres actives ; URL personnelle publique non retrouvée de façon fiable",
        "verified_email": "Aucun email de recrutement public vérifié",
        "email_status": "Ne pas utiliser une adresse supposée ; candidater depuis les offres LinkedIn. contact@focus-corporation.com est un contact commercial officiel, pas un canal RH.",
        "application_channel": "https://www.linkedin.com/jobs/view/4454710516/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "96",
        "sources": "https://www.linkedin.com/jobs/view/4454710516/ | https://www.linkedin.com/jobs/view/4448289528/ | https://www.linkedin.com/jobs/view/4450095019/ | https://focus-corporation.com/",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — deux offres entry-level et recruteuse actuelles",
        "notes": "Priorité très élevée. Candidater d'abord à ERP Development Engineer, où l'expérience antérieure est seulement un plus, puis à SAP BTP Technical Support Engineer.",
        "email_subject": "Candidature — ERP Development Engineer — Ingénieur ENSI",
        "email_body": "Bonjour Madame Hadded,\n\nJe vous adresse ma candidature au poste d’ERP Development Engineer chez Focus Corporation.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je possède de solides bases en développement logiciel, programmation orientée objet, SQL, PostgreSQL, Linux, Python, Java et C/C++. Mon PFE chez Linedata m’a permis de moderniser un produit financier complexe au moyen d’agents IA, en intervenant de l’analyse du besoin jusqu’aux tests, à l’intégration et à la documentation.\n\nL’opportunité de débuter dans l’écosystème ERP m’intéresse particulièrement : elle combine développement, compréhension des besoins métier, optimisation des données et apprentissage continu. Je ne maîtrise pas encore IBM i, DB2 ou RPG en contexte professionnel, mais je suis prêt à me former rapidement et mon parcours démontre ma capacité à prendre en main de nouveaux systèmes.\n\nJe joins mon CV et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour Mme Hadded, ingénieur ENSI récemment diplômé, je candidate au poste ERP Development Engineer chez Focus. Mon profil combine logiciel, SQL, Python/C++ et IA. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Hadded, merci d’avoir accepté mon invitation. Je viens de candidater au poste ERP Development Engineer. Je maîtrise SQL, Linux, Python, Java et C/C++, et je suis motivé pour me former rapidement à IBM i/DB2. Puis-je vous transmettre directement mon CV ?",
    },
    {
        "organization_key": "stb",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Ingénieur informatique, ingénieur sécurité informatique, Data/IA, audit IT ou transformation digitale bancaire",
        "match_score_10": "9.0",
        "match_reason": "Le concours 2026 comprenait exactement des postes Ingénieur en Informatique et Ingénieur en Sécurité Informatique ; le double profil informatique-finance est très pertinent.",
        "junior_status": "Oui — confirmé, mais concours 2026 clos",
        "junior_evidence": "Le concours externe 2026 prévoyait 6 postes d'ingénieur informatique et 2 postes d'ingénieur sécurité informatique sans expérience indiquée au tableau des profils.",
        "active_jobs": "Aucune offre active confirmée : concours STB 2026 clos depuis le 1er juillet 2026. Ne pas présenter ses 279 postes comme encore ouverts.",
        "linkedin_contact_name": "Amine Horrigue",
        "linkedin_contact_role": "Professionnel Ressources Humaines chez STB Bank",
        "linkedin_profile": "https://tn.linkedin.com/in/amine-horrigue-797b7b260",
        "contact_verification": "Profil actuel rattaché à STB Bank et activité RH 2026 vérifiés",
        "verified_email": "Aucun email public vérifié pour candidature spontanée",
        "email_status": "recrutement-2026@stb.com.tn était réservé aux recours du concours clos ; ne pas l'utiliser pour une candidature",
        "application_channel": "Page officielle STB / prochain concours public — aucun formulaire spontané vérifié",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "58",
        "sources": "https://www.emploi.rn.tn/fichiers/file_6a2083f51c41d5.56126517.pdf | https://fr.linkedin.com/posts/stb-bank_recrutementstbbank-offredemploi-concours-activity-7467489064573853696-A6DE | https://tn.linkedin.com/in/amine-horrigue-797b7b260",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — forte adéquation, concours 2026 explicitement clos",
        "notes": "Ne pas envoyer de candidature à l'adresse de recours du concours. Suivre la page STB et demander au contact RH si un prochain concours ou besoin IT est prévu.",
        "email_subject": "Candidature spontanée — Ingénieur informatique / Sécurité IT",
        "email_body": "Bonjour Monsieur Horrigue,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je souhaite vous faire part de mon intérêt pour de futures opportunités à la STB en ingénierie informatique, sécurité des systèmes d’information, Data/IA ou transformation digitale.\n\nJe sais que les inscriptions au concours 2026 sont désormais closes et je ne souhaite pas contourner cette procédure. Mon objectif est simplement de savoir quel canal suivre pour un prochain besoin correspondant à mon profil.\n\nMon PFE chez Linedata portait sur la modernisation d’un produit financier à l’aide d’agents IA. Je maîtrise également Python, Java, C++, le développement full-stack et les bases de données, avec une compréhension des enjeux bancaires apportée par ma spécialisation financière.\n\nJe serais ravi de vous transmettre mon CV FinTech si cela peut être utile pour un futur recrutement.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour M. Horrigue, ingénieur ENSI récemment diplômé en informatique et finance, je souhaite suivre les futures opportunités IT, sécurité et Data/IA de la STB après la clôture du concours 2026. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Horrigue, merci d’avoir accepté mon invitation. Je sais que le concours 2026 est clos. Pourriez-vous m’indiquer le bon canal à suivre pour une future opportunité d’ingénieur informatique, sécurité IT ou Data/IA à la STB ? Je peux vous transmettre mon CV FinTech.",
    },
    {
        "organization_key": "siemens",
        "sector": "Télécom / Électronique / Industrie",
        "target_roles": "Software Engineer C++, R&D Software Engineer, AI/ML Engineer ou ingénieur outils EDA",
        "match_score_10": "7.5",
        "match_reason": "Bonne base en C++, Python, algorithmique et logiciel, mais l'offre active exige aussi VHDL/Verilog, FPGA, Vivado/Quartus et STA non démontrés dans le CV.",
        "junior_status": "Oui — offre actuelle encadrée, malgré classification Mid-Senior",
        "junior_evidence": "L'offre indique travail sous supervision rapprochée, assistance aux ingénieurs seniors et compétences de base à niveau modéré ; Siemens accueille aussi des stagiaires et jeunes diplômés à Tunis.",
        "active_jobs": "Software Engineer — Tunis — https://tn.linkedin.com/jobs/view/software-engineer-at-siemens-eda-siemens-digital-industries-software-4444847273 — actif, mais compétences FPGA/HDL obligatoires",
        "linkedin_contact_name": "Youssef Weslati",
        "linkedin_contact_role": "Software Engineer chez Siemens EDA et ancien étudiant ENSI — contact réseau pertinent, non recruteur",
        "linkedin_profile": "https://tn.linkedin.com/in/youssef-weslati-6a8817222",
        "contact_verification": "Profil actuel Siemens EDA et lien ENSI vérifiés ; contacter avec une demande de conseil, pas comme recruteur",
        "verified_email": "Aucun email public vérifié",
        "email_status": "Candidature uniquement via l'offre officielle/LinkedIn Siemens",
        "application_channel": "https://tn.linkedin.com/jobs/view/software-engineer-at-siemens-eda-siemens-digital-industries-software-4444847273",
        "recommended_cv": "CV_ATS.pdf",
        "language": "en",
        "potential_score_100": "68",
        "sources": "https://tn.linkedin.com/jobs/view/software-engineer-at-siemens-eda-siemens-digital-industries-software-4444847273 | https://tn.linkedin.com/in/youssef-weslati-6a8817222 | https://tn.linkedin.com/in/marouene-haouati",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offre active, écart important sur FPGA/HDL",
        "notes": "Candidature possible seulement si le candidat souhaite se repositionner vers EDA/FPGA et peut démontrer une base crédible. Ne pas prétendre maîtriser VHDL, Verilog, Vivado ou Quartus.",
        "email_subject": "Application — Software Engineer — Tunis",
        "email_body": "Dear Hiring Team,\n\nI am applying for the Software Engineer position within Siemens EDA in Tunis. I recently graduated as a Computer Engineer from ENSI and have a strong foundation in C++, Python, algorithms, object-oriented development, Linux and Git.\n\nDuring my final-year project at Linedata, I contributed to the modernization of a complex financial software product through an agentic AI solution, from design and implementation to testing and integration. This experience strengthened my ability to understand large codebases, debug complex behavior and deliver maintainable software in collaboration with product teams.\n\nI want to be transparent that my current strengths are primarily in software engineering and AI rather than FPGA design. I am nevertheless highly motivated to build deeper expertise in HDL, FPGA tooling and hardware-assisted verification under the guidance of experienced engineers.\n\nPlease find my English CV attached. I would welcome the opportunity to discuss whether my software background and learning capacity could fit this position or another graduate-level role in Tunis.\n\nKind regards,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Hi Youssef, I’m a recent ENSI Computer Engineering graduate applying to Siemens EDA. My background is in C++, Python and AI, and I’d value your advice as a fellow ENSI alumnus on the Tunis software team.",
        "linkedin_followup": "Hi Youssef, thank you for connecting. I’m considering the current Software Engineer opening. My strengths are C++, Python and software/AI, while FPGA and HDL are areas I still need to develop. In your view, is the role realistic for a fast-learning graduate, or should I watch for another software opening?",
    },
    {
        "organization_key": "cognira",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Data Scientist junior, Data Engineer junior, Software Engineer, QA Automation ou support produit Data/AI",
        "match_score_10": "9.0",
        "match_reason": "Très bonne adéquation avec Python, IA/ML, logiciel et données ; Cognira développe un produit de retail analytics et promotion optimization fondé sur la Data Science.",
        "junior_status": "Oui — stages et recrutements juniors observés ; besoin actuel non confirmé",
        "junior_evidence": "Cognira a proposé des PFE à Tunis et emploie des profils de début de carrière ; le portail officiel est actif mais ne présentait pas de poste tunisien adapté lors de la vérification.",
        "active_jobs": "Aucune offre tunisienne junior adaptée confirmée sur le portail officiel : https://cognira.com/careers/",
        "linkedin_contact_name": "Mouna Belhadj",
        "linkedin_contact_role": "Global Talent Acquisition Specialist chez Cognira",
        "linkedin_profile": "https://tn.linkedin.com/in/mouna-belhadj/en",
        "contact_verification": "Profil actuel Cognira et activité Talent Acquisition récente vérifiés",
        "verified_email": "Aucun email public actuel vérifié",
        "email_status": "L'ancienne adresse careers-tunisia@cognira.com n'est pas réutilisée sans publication récente ; passer par le portail officiel ou LinkedIn",
        "application_channel": "https://cognira.com/careers/",
        "recommended_cv": "CV_ATS_EN.pdf",
        "language": "en",
        "potential_score_100": "72",
        "sources": "https://cognira.com/careers/ | https://cognira.com/life-at-cognira/ | https://tn.linkedin.com/in/mouna-belhadj/en | https://tn.linkedin.com/in/elias-bouricha-11b2b46",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — contact actuel, aucun poste junior tunisien confirmé",
        "notes": "Demander à Mouna Belhadj si un poste junior Data/Software/QA est prévu ; ne pas utiliser les anciennes offres comme actuelles.",
        "email_subject": "Spontaneous Application — Junior Data/AI or Software Engineer — Tunis",
        "email_body": "Dear Ms. Belhadj,\n\nI would like to express my interest in a junior Data, AI or Software Engineering opportunity at Cognira’s Tunis office.\n\nI recently graduated as a Computer Engineer from ENSI, with a specialization in Financial Engineering. My background combines Python, machine learning, databases, full-stack development and generative AI. During my final-year project at Linedata, I built an agentic AI solution to modernize a complex financial product, which required careful data handling, evaluation, integration and collaboration with product stakeholders.\n\nCognira’s use of advanced analytics to solve concrete retail and promotion-planning problems is particularly attractive to me because it connects technical depth with measurable business value. I would be glad to contribute in Data Science, Data Engineering, software development, QA automation or product support while continuing to grow.\n\nI have attached my English CV and would appreciate being considered for any suitable current or upcoming junior role in Tunis.\n\nKind regards,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Hi Mouna, I’m a recent ENSI Computer Engineering graduate with experience in Python, ML, software and agentic AI. I’m interested in junior Data/AI opportunities at Cognira Tunis and would be glad to connect.",
        "linkedin_followup": "Hi Mouna, thank you for connecting. My final-year project at Linedata combined software engineering, data and agentic AI. I’m looking for a junior Data Science, Data Engineering, Software or QA role in Tunis. May I send you my English CV for future Cognira openings?",
    },
    {
        "organization_key": "elyadata",
        "sector": "IA / Data / Logiciel",
        "target_roles": "AI Engineer junior, Data Scientist, Data Engineer, RAG/LLM Engineer ou ML Engineer",
        "match_score_10": "9.5",
        "match_reason": "Adéquation directe avec l'IA, les LLM, RAG, bases vectorielles, Python et l'industrialisation de solutions Data/AI.",
        "junior_status": "Oui — stages techniques récents ; emploi junior non confirmé",
        "junior_evidence": "Elyadata a accueilli récemment des stages hands-on en RAG, bases vectorielles et Data/AI, avec encadrement par ses ingénieurs.",
        "active_jobs": "Aucune offre d'emploi junior active vérifiée ; suivre la page entreprise et contacter un responsable technique pour une candidature spontanée",
        "linkedin_contact_name": "Nader Mechergui",
        "linkedin_contact_role": "Responsable/ingénieur IA chez Elyadata — contact technique pertinent, non recruteur",
        "linkedin_profile": "https://tn.linkedin.com/in/mecherguinader/fr",
        "contact_verification": "Profil actuel Elyadata et activité récente autour des stages IA vérifiés",
        "verified_email": "Aucun email public vérifié",
        "email_status": "Aucune adresse RH publique actuelle retrouvée ; contact LinkedIn ou page entreprise uniquement",
        "application_channel": "https://www.linkedin.com/company/elyadata/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "74",
        "sources": "https://tn.linkedin.com/in/mecherguinader/fr | https://tn.linkedin.com/in/mohamedbahariahi/ar | https://www.linkedin.com/company/elyadata/",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — forte adéquation et culture junior, aucun emploi actif confirmé",
        "notes": "Candidature spontanée très ciblée sur Agentic AI, RAG et évaluation. Demander un conseil technique à Nader, sans lui attribuer un rôle RH.",
        "email_subject": "Candidature junior — IA générative, RAG et Data Engineering",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite proposer ma candidature pour une première opportunité chez Elyadata en IA générative, Machine Learning ou Data Engineering.\n\nMon PFE chez Linedata portait sur la modernisation d’un produit financier complexe à l’aide de trois agents IA, d’une architecture RAG et de 24 outils d’intégration. J’ai ainsi travaillé sur la recherche contextuelle, l’orchestration d’agents, la qualité des résultats et l’intégration d’une solution IA dans un produit existant. Je maîtrise aussi Python, les bases de données, le machine learning et le développement full-stack.\n\nLes travaux récents d’Elyadata autour des bases vectorielles, du RAG et des plateformes Data/IA correspondent particulièrement à mes intérêts. Je serais heureux de contribuer à des projets concrets tout en approfondissant les pratiques de mise en production et d’évaluation.\n\nJe joins mon CV et reste disponible pour un échange.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Bonjour M. Mechergui, ingénieur ENSI récemment diplômé, mon PFE chez Linedata portait sur des agents IA et une architecture RAG. Les projets Data/IA d’Elyadata m’intéressent beaucoup. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Mechergui, merci d’avoir accepté mon invitation. Mon expérience couvre Python, LLM, RAG, bases de données et full-stack. Je recherche une première opportunité IA/Data. Pourriez-vous m’indiquer si Elyadata envisage des recrutements juniors et à qui transmettre mon CV ?",
    },
    {
        "organization_key": "keyrus",
        "sector": "IA / Data / Logiciel",
        "target_roles": "Data Engineer junior, BI Consultant junior, AI Engineer, Data Analyst ou consultant Data",
        "match_score_10": "8.5",
        "match_reason": "Bonne adéquation Data/IA, Python, SQL et compréhension métier ; les offres tunisiennes visibles demandent généralement une expérience Talend/ETL de 2 à 5 ans.",
        "junior_status": "Oui historiquement ; besoin tunisien actuel non confirmé",
        "junior_evidence": "Keyrus a intégré des Junior BI Consultants à Tunis, mais l'offre Data Engineer retrouvée est fermée et demandait 2 à 5 ans.",
        "active_jobs": "Aucune offre junior Tunisie active confirmée ; l'ancienne offre Data Engineer est fermée. Portail groupe : https://jobs.keyrus.fr/",
        "linkedin_contact_name": "Aucun recruteur Keyrus Tunisie actuel vérifié",
        "linkedin_contact_role": "Sabrine Arfaoui n'est plus chez Keyrus ; elle travaille actuellement chez Pentabell et ne doit pas être contactée comme recruteuse Keyrus",
        "linkedin_profile": "Aucun profil RH tunisien actuel vérifié",
        "contact_verification": "Ancien contact écarté après vérification de son employeur actuel",
        "verified_email": "Aucun email public actuel vérifié",
        "email_status": "L'ancienne adresse personnelle Keyrus n'est pas utilisée car sa titulaire a quitté l'entreprise",
        "application_channel": "https://jobs.keyrus.fr/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "fr",
        "potential_score_100": "58",
        "sources": "https://jobs.keyrus.fr/ | https://tn.linkedin.com/jobs/view/data-engineer-at-keyrus-4257170453 | https://tn.linkedin.com/in/sabrine-arfaoui-21167aa4 | https://tn.linkedin.com/in/ouni-koussay",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — ancien contact écarté, aucune offre tunisienne junior active",
        "notes": "Surveiller le portail. Ne pas écrire à Sabrine Arfaoui pour Keyrus : elle est désormais chez Pentabell.",
        "email_subject": "Candidature spontanée — Data, BI et Intelligence Artificielle",
        "email_body": "Bonjour,\n\nJe souhaite vous proposer ma candidature pour une première opportunité chez Keyrus Tunisie en Data Engineering, Business Intelligence, Data Analysis ou Intelligence Artificielle.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je maîtrise Python, SQL, les bases de données, le machine learning, l’IA générative et le développement full-stack. Mon PFE chez Linedata portait sur la modernisation d’un produit financier à l’aide d’agents IA et d’une architecture RAG, avec une forte dimension d’intégration et de qualité des données.\n\nLe positionnement de Keyrus autour de la Data, de l’Analytics et de l’IA correspond directement à mon projet professionnel. Je suis prêt à approfondir rapidement les outils ETL et BI propres à vos missions, notamment Talend, et à mettre mon profil technique et métier au service de projets clients.\n\nJe joins mon CV et reste disponible pour tout poste junior actuel ou futur à Tunis.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692",
        "linkedin_invitation": "Aucun contact RH tunisien actuel vérifié — utiliser le portail Keyrus et rechercher un Talent Acquisition Specialist encore rattaché à Keyrus Tunisie avant invitation.",
        "linkedin_followup": "Bonjour, merci d’avoir accepté mon invitation. Ingénieur ENSI récemment diplômé, je recherche une première opportunité Data, BI ou IA à Tunis. Mon PFE chez Linedata portait sur des agents IA et RAG. Puis-je vous transmettre mon CV ?",
    },
    {
        "organization_key": "oddo bhf",
        "sector": "Finance / Banque / FinTech",
        "target_roles": "Compliance Data & Analytics, Business/Data Analyst, AI Engineer junior, IT PMO ou Software Engineer FinTech",
        "match_score_10": "9.5",
        "match_reason": "Très forte adéquation entre ingénierie financière, Python, SQL, IA, Data et PFE FinTech ; l'offre actuelle accepte explicitement que les stages comptent comme expérience.",
        "junior_status": "Oui — confirmé",
        "junior_evidence": "ODDO BHF Tunis mène des programmes alternance pour jeunes talents IT et l'offre Compliance Data & Analytics accepte une première expérience, stages compris.",
        "active_jobs": "Compliance Data and Analytics Expert — Tunis — https://tn.linkedin.com/jobs/view/compliance-data-and-analytics-expert-at-oddo-bhf-4466545435 — 2 à 5 ans mais stages considérés | Offres IT actuelles — https://fr.linkedin.com/company/oddo-bhf/jobs",
        "linkedin_contact_name": "Sami Belhadj",
        "linkedin_contact_role": "Manager technique chez ODDO BHF Tunis, impliqué directement dans le recrutement IA/Python 2026",
        "linkedin_profile": "https://tn.linkedin.com/in/sbelhadj",
        "contact_verification": "Profil ODDO BHF actuel et publications de recrutement de septembre 2026 vérifiés ; contact technique, non RH",
        "verified_email": "talent.tunis@oddo-bhf.com",
        "email_status": "Adresse de recrutement générique publiée à plusieurs reprises par ODDO BHF ; préférer aussi la candidature directe à l'offre active",
        "application_channel": "https://tn.linkedin.com/jobs/view/compliance-data-and-analytics-expert-at-oddo-bhf-4466545435",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "fr",
        "potential_score_100": "91",
        "sources": "https://tn.linkedin.com/jobs/view/compliance-data-and-analytics-expert-at-oddo-bhf-4466545435 | https://fr.linkedin.com/company/oddo-bhf/jobs | https://tn.linkedin.com/in/sbelhadj | https://fr.linkedin.com/posts/sbelhadj_oddo-bhf-tunis-recrute-ses-derniers-alternants-activity-7503749274346852353-ExmV | https://fr.linkedin.com/posts/oddo-bhf_oddobhf-opportunitycreators-joboffers-activity-7114977655996723200-VizX",
        "checked_date": "2026-09-24",
        "verification_status": "Vérifié manuellement — offre Data/Compliance active et forte culture jeunes talents",
        "notes": "Candidature prioritaire même avec moins de deux ans : l'annonce précise que les stages peuvent être considérés. Mettre en avant le PFE Linedata, Python, finance, IA et la capacité à vulgariser les analyses.",
        "email_subject": "Candidature — Compliance Data and Analytics Expert — Profil junior ENSI/FinTech",
        "email_body": "Bonjour,\n\nJe vous adresse ma candidature au poste de Compliance Data and Analytics Expert au sein d’ODDO BHF Tunis.\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, mon profil réunit Python, SQL, analyse de données, intelligence artificielle et compréhension des métiers financiers. Lors de mon PFE chez Linedata, j’ai développé une solution composée d’agents IA pour moderniser un produit financier complexe, en portant une attention particulière à la qualité des données, à l’automatisation, à l’évaluation des résultats et à leur restitution aux équipes métier.\n\nJe débute ma carrière et ne dispose pas encore de deux années d’expérience salariée. Toutefois, l’annonce précise que les stages peuvent être considérés, et mon PFE ainsi que mes responsabilités de CTO m’ont permis de travailler sur des problématiques concrètes, de prioriser les besoins et de communiquer des résultats techniques de manière accessible.\n\nLa dimension internationale du poste et son croisement entre Compliance, Data, automatisation et IA correspondent exactement à mon projet professionnel. Je joins mon CV FinTech et reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul\nmohamedoussema.bahloul@ensi-uma.tn | +216 50 606 692\nlinkedin.com/in/mohamedoussemabahloul",
        "linkedin_invitation": "Bonjour M. Belhadj, ingénieur ENSI récemment diplômé en informatique et finance, je candidate au poste Compliance Data & Analytics chez ODDO BHF. Mon PFE Linedata portait sur Python et des agents IA. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Belhadj, merci d’avoir accepté mon invitation. Je viens de candidater au poste Compliance Data & Analytics. Mon profil combine Python, SQL, finance et IA agentique, et l’annonce indique que les stages peuvent compter. Accepteriez-vous de me conseiller sur l’adéquation de mon profil junior ?",
    },
]


def main() -> None:
    fields = sorted({key for record in RECORDS for key in record})
    fields.remove("organization_key")
    fields.insert(0, "organization_key")
    with OUTPUT.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(RECORDS)
    print(f"Wrote {len(RECORDS)} verified records to {OUTPUT}")


if __name__ == "__main__":
    main()
