#!/usr/bin/env python3
"""Verified Tunisia research batch checked on 2026-09-25."""

from __future__ import annotations

import csv
from pathlib import Path


OUT = Path(__file__).resolve().parent / "verified_batches" / "batch_2026_09_25_05.csv"


RECORDS = [
    {
        "organization_key": "athena technology services ats",
        "sector": "ESN et développement digital: web/mobile, Data, cloud, DevOps et conseil",
        "target_roles": "Software Engineer junior; développeur Python/Java/full-stack junior; Data Engineer junior; DevOps junior; Business Analyst IT junior",
        "match_score_10": "8.2",
        "match_reason": "ATS intervient sur le développement, la Data et le conseil, directement alignés avec le socle ENSI, le full-stack, Python/Java et le PFE en IA. Les offres actuellement publiées sont toutefois senior ou freelance.",
        "junior_status": "Oui — historique confirmé, ouverture actuelle non confirmée",
        "junior_evidence": "ATS a déjà recruté des intégrateurs Data juniors et accueilli des PFE en full-stack, mobile et Data. Le formulaire actuel accepte la candidature spontanée et permet d'indiquer le niveau d'expérience.",
        "active_jobs": "Développeur Web Senior Symfony — Tunis/Paris — page officielle accessible, publiée 2025-12-07 — non adaptée au niveau junior — https://www.ats-digital.com/nous-rejoindre/ | Odoo Freelancer — publication 2025-07-21 — non adaptée. Aucune offre junior active confirmée le 2026-09-25.",
        "linkedin_contact_name": "Amine Miled",
        "linkedin_contact_role": "Cofondateur — ATS Digital Dev",
        "linkedin_profile": "https://tn.linkedin.com/in/amine-miled-ats-7545a111b",
        "contact_verification": "Profil actuel ATS et cofondateur, avec activité récente relayant les besoins .NET, DevOps et les hackathons de l'entreprise.",
        "verified_email": "recrutement@ats-digital.com",
        "email_status": "Adresse publiée sur le formulaire de candidature et la page carrières officiels ATS.",
        "application_channel": "https://www.ats-digital.com/postuler/ | mailto:recrutement@ats-digital.com",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "65",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Bureaux tunisiens aux Berges du Lac, Tunis.",
        "sources": "https://www.ats-digital.com/postuler/ | https://www.ats-digital.com/nous-rejoindre/ | https://tn.linkedin.com/in/amine-miled-ats-7545a111b",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — email et candidature spontanée officiels, aucune offre junior active",
        "notes": "Les deux lignes ATS du CSV sont consolidées. Candidature spontanée recommandée ; ne pas citer les anciennes annonces 2019 comme actuelles.",
        "email_subject": "Candidature spontanée – Ingénieur informatique junior | Software, Data et IA",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite proposer ma candidature pour une première opportunité chez ATS dans le développement logiciel, la Data, l'IA ou le conseil IT.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier à l'aide d'agents IA. J'y ai appris à partir d'un besoin métier, construire une solution, l'intégrer à un produit existant et travailler avec rigueur dans un environnement exigeant. Je maîtrise Python, Java, C++, le développement full-stack, les bases de données, les APIs et les principes de machine learning et d'IA générative.\n\nLa combinaison chez ATS du développement, de la Data et de l'accompagnement métier correspond à ma polyvalence et à mon envie de progresser sur des projets concrets. Je suis ouvert à tout poste junior cohérent avec ma formation, y compris en software engineering, Data, automatisation ou Business Analysis IT.\n\nMon CV est joint. Je serais ravi d'échanger sur un besoin actuel ou futur.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Miled, jeune diplômé ingénieur ENSI, je recherche une première opportunité en software, Data ou IA. Le positionnement d'ATS entre développement, conseil et innovation correspond bien à mon parcours. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Miled, merci pour la connexion. J'ai transmis une candidature spontanée à recrutement@ats-digital.com. Mon profil combine Python/Java/C++, full-stack, Data/IA et un PFE Linedata sur des agents IA. Si un besoin junior existe ou se prépare, je serais reconnaissant de pouvoir être orienté vers la bonne équipe.",
    },
    {
        "organization_key": "aymax",
        "sector": "Conseil, intégration SAP, développement digital, Data et IA prédictive/générative",
        "target_roles": "Consultant SAP junior; développeur SAP ABAP/Fiori junior; Software Engineer junior; Business Analyst IT junior; Data/AI Engineer junior; QA Automation junior",
        "match_score_10": "8.4",
        "match_reason": "AYMAX valorise à la fois le développement, SAP, les processus métier et l'IA. Le profil informatique-finance est particulièrement intéressant pour SAP FICO, l'analyse fonctionnelle et les solutions digitales, même sans expérience SAP professionnelle.",
        "junior_status": "Oui",
        "junior_evidence": "AYMAX annonce rechercher continuellement de nouveaux talents, accueille des promotions PFE à Tunis et publie des témoignages de stagiaires devenus consultants SAP. Quatorze nouveaux PFE ont encore été accueillis à Tunis en 2026.",
        "active_jobs": "Aucune offre tunisienne junior parfaitement adaptée n'a été confirmée le 2026-09-25. Les annonces AYMAX récentes trouvées visent surtout des consultants SAP confirmés/seniors en France. Candidature spontanée via le portail officiel recommandée.",
        "linkedin_contact_name": "Marwa Ayari",
        "linkedin_contact_role": "Manager Recrutement & Marque Employeur — AYMAX",
        "linkedin_profile": "https://fr.linkedin.com/in/aymax-consulting",
        "contact_verification": "Profil AYMAX actif avec publication de recrutements en 2026 et titre public Manager Recrutement & Marque Employeur.",
        "verified_email": "contact-it@aymax.fr",
        "email_status": "Adresse générale officielle publiée pour le bureau de Tunis. marwa.ayari@aymax.fr apparaît dans ses publications de recrutement, mais l'adresse générale et le portail restent les canaux prioritaires.",
        "application_channel": "https://aymax.fr/recrutement-aymax/ | mailto:contact-it@aymax.fr",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "Français",
        "potential_score_100": "75",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Bureau AYMAX aux Berges du Lac II, Tunis.",
        "sources": "https://aymax.fr/recrutement-aymax/ | https://aymax.fr/contacts/ | https://aymax.fr/ | https://fr.linkedin.com/in/aymax-consulting | https://fr.linkedin.com/posts/aymax-consulting_14-nouveaux-talents-nous-rejoignent-%C3%A0-tunis-activity-7430175968868282368-PaFw",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — forte culture junior/PFE et canal officiel, aucune offre junior exacte confirmée",
        "notes": "Positionner le profil sur SAP/digital/IA et la compréhension finance, sans prétendre maîtriser SAP. Le CV FinTech est le meilleur choix pour SAP FICO et transformation des processus.",
        "email_subject": "Candidature junior – Consultant SAP/Digital | Ingénieur informatique et financière",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, avec une spécialisation en ingénierie financière, je souhaite rejoindre AYMAX pour débuter ma carrière dans le conseil SAP, la transformation digitale ou le développement de solutions intelligentes.\n\nMon PFE chez Linedata a consisté à moderniser un produit financier à l'aide d'agents IA. Cette expérience m'a appris à comprendre un processus métier, dialoguer avec différents interlocuteurs et transformer le besoin en une solution logicielle utile. Je maîtrise Python, Java, C++, le développement full-stack, SQL, les APIs, la Data et l'IA générative.\n\nJe ne présente pas encore d'expérience professionnelle SAP, mais ma double culture informatique-finance, ma capacité d'apprentissage et mon intérêt pour les processus d'entreprise constituent une base solide pour évoluer vers SAP FICO, le conseil fonctionnel/technique ou la Business Analysis. L'accompagnement des jeunes talents chez AYMAX renforce particulièrement ma motivation.\n\nJe joins mon CV et reste ouvert à tout poste junior cohérent avec mon parcours.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Madame Ayari, jeune diplômé ingénieur ENSI spécialisé en ingénierie financière, je m'intéresse aux parcours juniors AYMAX en SAP, digital et IA. Mon PFE Linedata portait sur des agents IA appliqués à un produit financier. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Madame Ayari, merci pour la connexion. J'ai déposé une candidature junior chez AYMAX. Ma double formation informatique-finance peut notamment servir les métiers SAP FICO, Business Analysis, développement ou IA. Sans prétendre déjà maîtriser SAP, je suis très motivé à me former. Pourriez-vous m'indiquer les équipes ou futures campagnes juniors à suivre ?",
    },
    {
        "organization_key": "b2m",
        "sector": "Intégration Microsoft, ERP/Business Central, Business Intelligence, cloud et infrastructure IT",
        "target_roles": "Consultant ERP/Business Central junior; consultant BI junior; Data Analyst junior; Software Engineer junior; Business Analyst IT junior; ingénieur systèmes junior",
        "match_score_10": "7.7",
        "match_reason": "La formation informatique-finance est pertinente pour l'ERP, la BI et la digitalisation des processus. L'offre actuelle d'administrateur systèmes junior confirme l'ouverture aux débutants mais cible un technicien supérieur et l'administration Microsoft, moins alignée qu'un rôle ingénieur ERP/Data.",
        "junior_status": "Oui",
        "junior_evidence": "B2M-IT publie actuellement un poste de Technicien Supérieur IT / Administrateur Systèmes Junior à Tunis et a déjà recruté des commerciaux juniors. L'entreprise possède aussi des activités de conseil BI et ERP.",
        "active_jobs": "Technicien Supérieur IT / Administrateur Systèmes Junior — Tunis — publication LinkedIn accessible le 2026-09-25 — https://tn.linkedin.com/jobs/view/technicien-sup%C3%A9rieur-it-administrateur-syst%C3%A8mes-junior-at-b2m-it-4384455706 — junior mais sous-emploi possible pour un diplôme d'ingénieur.",
        "linkedin_contact_name": "Mohamed Laajili",
        "linkedin_contact_role": "Chef d'équipe — B2M-IT",
        "linkedin_profile": "https://tn.linkedin.com/in/laajili-mohammed",
        "contact_verification": "Profil actuel B2M-IT annonçant récemment sa prise de poste comme chef d'équipe. Contact technique pertinent, pas RH.",
        "verified_email": "info@b2m-it.com",
        "email_status": "Adresse publiée sur le site carrière officiel B2M-IT et dans une annonce LinkedIn de l'entreprise. L'email nominatif du CSV n'est pas utilisé faute de nécessité.",
        "application_channel": "https://b2m-it.com/Carriere-location/tunisie/ | mailto:info@b2m-it.com",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "Français",
        "potential_score_100": "70",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Implantation à Tunis.",
        "sources": "https://tn.linkedin.com/jobs/view/technicien-sup%C3%A9rieur-it-administrateur-syst%C3%A8mes-junior-at-b2m-it-4384455706 | https://b2m-it.com/Carriere-location/tunisie/ | https://tn.linkedin.com/in/laajili-mohammed",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — ouverture junior actuelle, meilleur ciblage recommandé vers ERP/BI",
        "notes": "Ne pas privilégier le poste Technicien Supérieur si l'objectif est un métier d'ingénieur. Envoyer plutôt une candidature ciblée ERP/BI/Data/Business Analysis, tout en indiquant l'ouverture aux fonctions systèmes de niveau ingénieur.",
        "email_subject": "Candidature junior – Consultant ERP/BI | Ingénieur informatique et financière",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, avec une spécialisation en ingénierie financière, je souhaite proposer ma candidature à B2M-IT pour une première opportunité dans l'ERP, la Business Intelligence, la Data ou la transformation digitale.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier avec des agents IA. J'ai ainsi développé une double capacité à comprendre les processus métier et à construire des solutions logicielles. Je maîtrise Python, Java, C++, SQL, le développement full-stack, les bases de données, le machine learning et l'IA générative.\n\nL'écosystème Microsoft, ERP et BI de B2M-IT correspond bien à mon profil hybride. Je pourrais évoluer vers le conseil Business Central, l'analyse de données, la Business Analysis ou le développement de solutions, en mobilisant aussi ma compréhension des enjeux financiers. Je suis également disposé à renforcer rapidement mes compétences sur les outils spécifiques utilisés par vos équipes.\n\nJe joins mon CV et serais heureux d'échanger sur vos besoins juniors actuels ou futurs.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Laajili, jeune diplômé ingénieur ENSI spécialisé en ingénierie financière, je m'intéresse aux métiers ERP, BI et Data chez B2M-IT. Mon PFE Linedata portait sur des agents IA appliqués à un produit financier. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Laajili, merci pour la connexion. J'ai adressé à B2M-IT une candidature orientée ERP/BI/Data. Mon profil combine ingénierie logicielle, finance et IA. L'offre systèmes junior confirme que l'équipe se développe, mais je vise idéalement un rôle d'ingénieur ERP, BI ou Business Analysis. Pourriez-vous m'orienter vers l'interlocuteur pertinent ?",
    },
    {
        "organization_key": "centre informatique du ministere de la sante",
        "sector": "Administration publique, e-santé, systèmes d'information hospitaliers, cybersécurité et transformation numérique",
        "target_roles": "Ingénieur informatique santé; développeur SI hospitalier; Data/AI Engineer e-santé; ingénieur cybersécurité/SOC; Business Analyst SI santé",
        "match_score_10": "8.0",
        "match_reason": "Le CIMS développe et déploie des SI hospitaliers et mène des initiatives en IA, cybersécurité et transformation numérique. Python, logiciel, Data/IA et cybersécurité sont pertinents, mais le recrutement public suit généralement un concours spécifique.",
        "junior_status": "Oui — concours et stages, concours actuel clos/non confirmé",
        "junior_evidence": "Un concours externe publié en janvier 2026 portait sur six postes d'ingénieur principal en informatique médicale. Des PFE 2026 au CIMS ont concerné un SOC fondé sur l'IA, confirmant l'accueil de jeunes informaticiens.",
        "active_jobs": "Aucun concours de recrutement CIMS encore ouvert n'a été confirmé le 2026-09-25. Le concours externe publié le 2026-01-28 est ancien et n'est pas présenté comme actif. L'AMI de refonte du SI hospitalier clôturé le 2026-02-16 concernait des consultants/prestataires, pas une embauche individuelle.",
        "linkedin_contact_name": "Taoufik Borgi",
        "linkedin_contact_role": "Chargé de la supervision de la gestion du CIMS",
        "linkedin_profile": "https://tn.linkedin.com/in/taoufik-borgi-95578823a",
        "contact_verification": "Identifié en 2026 par le Healthcare IT Forum comme chargé de la supervision de la gestion du CIMS ; profil public actuel au Ministère de la Santé.",
        "verified_email": "cims@rns.tn",
        "email_status": "Adresse institutionnelle publiée dans plusieurs documents publics. Aucun email RH dédié actuel n'a été trouvé.",
        "application_channel": "https://www.linkedin.com/company/cimstunisie/ | mailto:cims@rns.tn",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "57",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Établissement public tunisien à Tunis.",
        "sources": "https://www.linkedin.com/company/cimstunisie/ | https://tn.linkedin.com/in/taoufik-borgi-95578823a | https://tn.linkedin.com/in/tasnim-benmbarek-521830285 | https://www.orientini.com/AR/Annonces_Orientation_Formation_Emploi/16820/ | https://www.marchespublics.gov.tn/fr/appels-doffres/Tender-100188 | https://realites.com.tn/fr/wp-content/uploads/2024/06/forum-sanofi-27-juin.pdf",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — concours antérieur et stages juniors, aucune ouverture actuelle confirmée",
        "notes": "La candidature spontanée sert à demander une orientation et ne remplace pas le concours public. Surveiller les annonces officielles du CIMS, du ministère et de l'emploi public.",
        "email_subject": "Demande d'orientation – Futurs concours d'ingénieur informatique au CIMS",
        "email_body": "Bonjour Madame, Monsieur,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite manifester mon intérêt pour les futurs concours ou opportunités du CIMS dans les systèmes d'information de santé, le développement, la Data/IA ou la cybersécurité.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier à l'aide d'agents IA. Il m'a permis de renforcer mes compétences en Python, développement logiciel, APIs, bases de données et intelligence artificielle dans un environnement où la fiabilité et la protection de l'information sont essentielles. Je maîtrise également Java, C++, le full-stack et les fondamentaux de la cybersécurité.\n\nLa mission du CIMS, qui consiste à améliorer les services de santé grâce aux systèmes d'information et à la transformation numérique, donne un sens concret aux compétences que je souhaite développer. Je serais particulièrement motivé par un poste d'ingénieur permettant de contribuer aux SI hospitaliers, à la sécurité ou à l'exploitation responsable de l'IA en santé.\n\nConscient que le recrutement suit des procédures de concours, je vous serais reconnaissant de m'indiquer les canaux à surveiller pour les prochains appels correspondant à mon profil. Mon CV est joint.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Borgi, jeune diplômé ingénieur ENSI, je m'intéresse à la transformation numérique de la santé, aux SI hospitaliers et à l'IA/cybersécurité. La mission du CIMS correspond fortement à mon projet. Je serais honoré de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Borgi, merci pour la connexion. Mon PFE Linedata portait sur des agents IA intégrés à un produit sensible. Je souhaite appliquer mes compétences Python, logiciel, Data/IA et cybersécurité à l'e-santé. Pourriez-vous m'indiquer où suivre les prochains concours ou besoins d'ingénieurs du CIMS ?",
    },
    {
        "organization_key": "centre national informatique",
        "sector": "Administration électronique, e-gouvernement, développement de SI, hébergement, réseaux, cybersécurité et transformation numérique publique",
        "target_roles": "Ingénieur informatique; développeur logiciel; Data/AI Engineer secteur public; ingénieur cloud/réseaux/sécurité; chef de projet SI junior",
        "match_score_10": "7.9",
        "match_reason": "Le CNI couvre développement, hébergement, réseaux, sécurité et projets de transformation de l'État. Le socle ENSI et le profil logiciel/Data/IA sont adaptés, notamment aux projets d'identité numérique et d'interopérabilité. L'accès dépend cependant des procédures de recrutement public.",
        "junior_status": "Oui — stages/PFE observés, concours actuel non confirmé",
        "junior_evidence": "Des étudiants et jeunes ingénieurs ont réalisé récemment au CNI des PFE sur une plateforme eKYC mêlant logiciel, IA et DevOps, ainsi que des stages en BI et développement. Aucun concours 2026 encore ouvert n'a toutefois été identifié.",
        "active_jobs": "Aucun concours ou poste d'ingénieur officiellement ouvert au CNI n'a été confirmé le 2026-09-25. Candidature d'orientation uniquement, en attendant une annonce officielle.",
        "linkedin_contact_name": "Imed Yazidi",
        "linkedin_contact_role": "Consultant et auditeur senior — Centre National de l'Informatique",
        "linkedin_profile": "https://tn.linkedin.com/in/imed-yazidi-2722b9a4",
        "contact_verification": "Profil public actuel du CNI, orienté pilotage, audit et sécurité SI. Contact métier pertinent mais non RH.",
        "verified_email": "webcni@cni.tn",
        "email_status": "Adresse générale publiée sur la page de contact officielle du CNI. Les emails des directions publiés sont fonctionnels, mais aucun canal RH dédié n'a été identifié.",
        "application_channel": "https://www.cni.tn/index.php/fr/contact-suggestion-2 | mailto:webcni@cni.tn",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "54",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Établissement public tunisien à Tunis.",
        "sources": "https://www.cni.tn/ | https://www.cni.tn/index.php/fr/contact-suggestion-2 | https://fr.linkedin.com/company/centre-national-de-l%27informatique | https://tn.linkedin.com/in/imed-yazidi-2722b9a4 | https://tn.linkedin.com/in/ismail-zenati",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — contact institutionnel et accueil de PFE, aucun recrutement ouvert confirmé",
        "notes": "Les deux variantes CNI du CSV sont consolidées. Utiliser le message comme demande d'orientation vers les prochains concours et non comme candidature à une offre inexistante.",
        "email_subject": "Demande d'orientation – Opportunités d'ingénieur informatique au CNI",
        "email_body": "Bonjour Madame, Monsieur,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, je souhaite manifester mon intérêt pour les futurs concours ou besoins du Centre National de l'Informatique dans le développement logiciel, la Data/IA, le cloud, la cybersécurité ou la conduite de projets SI.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier avec des agents IA. J'ai travaillé de la compréhension du besoin à l'intégration de la solution, en développant mes compétences en Python, APIs, bases de données, intelligence artificielle et qualité logicielle. Je maîtrise également Java, C++, le développement full-stack et Git.\n\nLes missions du CNI autour de l'administration électronique, de l'interopérabilité, de l'hébergement et de la sécurité correspondent à mon souhait de contribuer à des projets numériques utiles à grande échelle. Je serais notamment intéressé par tout rôle junior d'ingénieur logiciel, Data/IA, systèmes ou sécurité.\n\nConscient des procédures propres au secteur public, je vous serais reconnaissant de m'indiquer où suivre les prochains concours ou appels adaptés à mon profil. Mon CV est joint.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Monsieur Yazidi, jeune diplômé ingénieur ENSI, je m'intéresse aux projets du CNI en e-gouvernement, logiciel, Data/IA et sécurité. Mon PFE Linedata concernait des agents IA intégrés à un produit financier. Je serais ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Monsieur Yazidi, merci pour la connexion. Je souhaite mettre mes compétences Python, logiciel, Data/IA et cybersécurité au service de projets publics numériques. N'ayant trouvé aucun concours CNI encore ouvert, pourriez-vous m'indiquer les canaux ou futures campagnes à surveiller pour un jeune ingénieur ?",
    },
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(RECORDS[0]))
        writer.writeheader()
        writer.writerows(RECORDS)
    print(f"Wrote {len(RECORDS)} records to {OUT}")


if __name__ == "__main__":
    main()
