#!/usr/bin/env python3
"""Verified research batch checked on 2026-09-25."""

from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "verified_batches" / "batch_2026_09_25_10.csv"

RECORDS = [
    {
        "organization_key": "macquarie university cyber security hub",
        "sector": "Recherche universitaire en cybersécurité, confidentialité, IA, NLP et détection de menaces",
        "target_roles": "Research Software Engineer; Research Assistant en IA/cybersécurité; ingénieur ML/NLP; doctorant",
        "match_score_10": "8.0",
        "match_reason": "Les travaux du Hub sur les agents conversationnels malveillants, le NLP, le machine learning et la sécurité correspondent à l'IA agentique, Python et au développement logiciel du candidat. En revanche, les emplois visibles sont surtout académiques et le poste cyber actuellement affiché exige une solide carrière de recherche et d'enseignement.",
        "junior_status": "Oui, ponctuellement par stages et postes d'assistant de recherche",
        "junior_evidence": "Le Hub a publié un stage rémunéré pour étudiants en informatique/ingénierie/mathématiques, avec des sujets IA, NLP et cyber. La page officielle précise désormais que la date limite est passée. Aucun poste junior actuel correspondant n'est confirmé.",
        "active_jobs": "Aucun poste junior adapté confirmé ouvert le 2026-09-25. Le stage IA/cyber du Hub indique explicitement que la date limite est passée — https://www.mq.edu.au/partner/access-business-opportunities/innovation-entrepreneurship-and-it/cyber-security-hub/news/news/internship-opportunity!. Un poste Lecturer/Senior Lecturer in Cyber Security est ouvert, mais exige un excellent parcours de recherche et d'enseignement et ne correspond pas à un jeune diplômé — https://mq.wd3.myworkdayjobs.com/en-US/CareersatMQ/job/Senior-Lecturer-in-Cyber-Security_R000022247.",
        "linkedin_contact_name": "Dali Kaafar",
        "linkedin_contact_role": "Professor et Executive Director — Macquarie University Cyber Security Hub",
        "linkedin_profile": "https://au.linkedin.com/in/dali-kaafar-12b5b85",
        "contact_verification": "Fonction actuelle confirmée par le profil officiel Macquarie et par ses activités publiques 2026. Il dirige scientifiquement le Hub; il ne s'agit pas d'un recruteur généraliste.",
        "verified_email": "dali.kaafar@mq.edu.au",
        "email_status": "Adresse institutionnelle publiée sur le profil officiel de Macquarie. À utiliser uniquement pour une demande scientifique ciblée et non comme boîte RH générale.",
        "application_channel": "https://mq.wd3.myworkdayjobs.com/CareersatMQ | mailto:dali.kaafar@mq.edu.au",
        "recommended_cv": "CV_ATS_EN.pdf",
        "language": "Anglais",
        "potential_score_100": "37",
        "foreign_employee_status": "Oui, sous conditions et selon le poste",
        "foreign_employee_evidence": "La politique officielle actuelle prévoit qu'en circonstances approuvées Macquarie peut sponsoriser des travailleurs internationaux qualifiés, à la discrétion de l'université et selon le métier/contrat. Les stages étudiants et certaines annonces peuvent toutefois exiger des droits de travail locaux; aucune promesse n'existe pour un poste junior précis.",
        "sources": "https://researchers.mq.edu.au/en/persons/dali-kaafar | https://au.linkedin.com/in/dali-kaafar-12b5b85 | https://www.mq.edu.au/partner/access-business-opportunities/innovation-entrepreneurship-and-it/cyber-security-hub/news/news/internship-opportunity! | https://mq.wd3.myworkdayjobs.com/en-US/CareersatMQ/job/Senior-Lecturer-in-Cyber-Security_R000022247 | https://policies.mq.edu.au/document/view.php?id=404",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — bon alignement scientifique, aucune ouverture junior actuelle",
        "notes": "Priorité faible pour un emploi immédiat. Ne pas candidater au stage fermé ni au poste de lecturer. Envoyer seulement une demande courte sur de futurs rôles Research Assistant/Research Software Engineer et demander explicitement l'éligibilité internationale.",
        "email_subject": "Prospective Junior AI/Cybersecurity Research Engineer — ENSI Graduate",
        "email_body": "Dear Professor Kaafar,\n\nI am a recent Computer Engineering graduate from ENSI in Tunisia, with a specialisation in Financial Engineering, and I am writing to express my interest in future junior research engineering opportunities at the Macquarie University Cyber Security Hub.\n\nMy final-year project at Linedata focused on modernising a financial software product with AI agents. It strengthened my ability to connect an operational need with Python-based intelligent workflows and their integration into an existing application. My background also includes machine learning, LLM/RAG systems, APIs, databases, Java and C++.\n\nI was particularly interested in the Hub's work on malicious conversational agents, information leakage in NLP models and AI-enabled cyber-threat analysis. I understand that the internship page is closed and that the current Lecturer position is not suited to an early-career engineer. I am therefore not applying to an expired or unsuitable vacancy.\n\nCould you please advise whether the Hub expects future Research Assistant or Research Software Engineer opportunities open to a recent international graduate, and whether visa sponsorship could be considered for such a position? I have attached my English CV for context.\n\nKind regards,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Hello Professor Kaafar, I am a recent ENSI Computer Engineering graduate whose Linedata project used AI agents in financial software. Your Hub's work on conversational AI, NLP privacy and cyber-threat analysis strongly interests me. I would be glad to follow future junior research roles.",
        "linkedin_followup": "Thank you for connecting, Professor Kaafar. I found no currently open junior role at the Hub, so I have not treated the closed internship as active. I sent a concise enquiry about future Research Assistant or Research Software Engineer opportunities and international eligibility. My profile combines AI agents, Python and product integration.",
    },
    {
        "organization_key": "mat it",
        "sector": "Développement web et mobile, Drupal/Symfony/PHP, JavaScript, QA, cloud, DevOps et intégrations IA",
        "target_roles": "Ingénieur full-stack junior; AI/NLP Engineer junior; QA Automation Engineer; Software Engineer; API/Backend Developer",
        "match_score_10": "8.4",
        "match_reason": "Le diplôme ENSI, le full-stack, les APIs, les bases de données et l'IA correspondent directement aux profils publiés par Mat-IT. L'écart principal est leur stack très orientée PHP/Drupal/Symfony, moins centrale dans le CV que MERN, Python et Java.",
        "junior_status": "Oui — stages et profils ingénieurs en croissance",
        "junior_evidence": "L'entreprise a publié en 2026 un stage QA Tester pour étudiant et auparavant un stage rémunéré AI/NLP ainsi qu'un PFE à perspective pré-embauche. Son annonce Fullstack recommandait explicitement des diplômes ENSI/INSAT/SUP'COM/ENIT/ENIS/ISI sans indiquer un nombre d'années obligatoire.",
        "active_jobs": "Une offre Children’s Game Art / Graphic Designer est visible depuis environ un mois mais ne correspond pas au candidat. Aucun poste actif d'ingénieur logiciel/IA confirmé le 2026-09-25. Le stage QA de l'été 2026 (environ trois mois) et l'annonce Fullstack (environ douze mois) sont conservés comme preuves de recrutement, pas comme offres actives — https://www.linkedin.com/company/mat-it-agency.",
        "linkedin_contact_name": "Mohamed Anis TAKTAK",
        "linkedin_contact_role": "Dirigeant/fondateur et contact de recrutement — Mat-IT Web Development Agency",
        "linkedin_profile": "https://tn.linkedin.com/in/mohamedanistaktak",
        "contact_verification": "Profil listé parmi les employés actuels de la page officielle Mat-IT; l'adresse anis@mat-it.tech a été publiée par l'entreprise pour ses recrutements 2026.",
        "verified_email": "anis@mat-it.tech",
        "email_status": "Adresse vérifiée dans la publication officielle du stage QA 2026. Elle peut recevoir une candidature spontanée ciblée, sans prétendre qu'une offre technique est ouverte.",
        "application_channel": "mailto:anis@mat-it.tech | message direct à https://www.linkedin.com/company/mat-it-agency",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "64",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Le bureau concerné se trouve à Ennasr 2, Ariana; certaines missions sont internationales mais la candidature vise l'équipe tunisienne.",
        "sources": "https://www.linkedin.com/company/mat-it-agency | https://tn.linkedin.com/in/mohamedanistaktak | https://tn.linkedin.com/jobs/view/summer-internship-%E2%80%93-ai-nlp-engineer-at-mat-it-web-development-agency-4231836470 | https://www.recruter.tn/poste/opportunite-de-stage-pfe-chez-mat-it-agency/",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — junior-friendly, aucune offre technique actuelle confirmée",
        "notes": "Priorité moyenne-haute en candidature spontanée. Ne pas citer le poste de designer. Mettre en avant l'ENSI, l'intégration IA dans des produits, le full-stack, les APIs, le testing et la faculté d'apprendre PHP/Drupal si nécessaire.",
        "email_subject": "Candidature spontanée — Ingénieur logiciel / IA junior ENSI",
        "email_body": "Bonjour Monsieur Taktak,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, avec une spécialisation en ingénierie financière, je souhaite vous proposer ma candidature spontanée pour une première opportunité en développement logiciel, full-stack, QA automatisée ou intégration de fonctionnalités IA chez Mat-IT.\n\nLors de mon PFE chez Linedata, j'ai contribué à moderniser un produit financier grâce à des agents IA, en reliant compréhension du besoin, conception de workflows intelligents et intégration dans une application existante. Je maîtrise Python, Java, C++, JavaScript, le développement full-stack, les APIs, SQL et les bases de données, ainsi que le machine learning et les LLM.\n\nMat-IT m'intéresse par sa manière de réunir développement web, qualité logicielle, cloud et innovation IA dans des projets concrets. Mon socle logiciel me permet d'être rapidement opérationnel tout en montant en compétence sur votre environnement PHP, Drupal et Symfony.\n\nJe n'ai pas identifié aujourd'hui d'offre technique encore ouverte correspondant à mon profil; je vous adresse donc une candidature spontanée transparente. Je serais heureux d'échanger si un besoin junior actuel ou prochain peut correspondre à mon parcours.\n\nVous trouverez mon CV en pièce jointe.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour M. Taktak, diplômé ingénieur ENSI, j'ai réalisé chez Linedata un PFE mêlant agents IA et intégration produit. Le positionnement web, QA, cloud et IA de Mat-IT correspond à mon profil logiciel/full-stack. Je viens de vous adresser une candidature spontanée ciblée. Ravi de vous rejoindre.",
        "linkedin_followup": "Bonjour M. Taktak, merci pour la connexion. Je vous ai envoyé à anis@mat-it.tech une candidature spontanée pour un rôle junior logiciel, full-stack, QA ou IA. Je n'ai pas présenté les anciennes annonces comme actives. Mon CV met en avant l'ENSI, mon PFE Linedata, Python/Java/C++, les APIs, SQL et ma capacité à apprendre votre stack Drupal/Symfony.",
    },
    {
        "organization_key": "tanitlab",
        "sector": "Data, intelligence artificielle, Google Cloud, Data Engineering et solutions RegTech/FinTech de risque et conformité",
        "target_roles": "Junior Data Scientist; Junior AI/ML Engineer; Data Engineer; Cloud/Data Developer; Software Engineer IA; analyste Data/risque",
        "match_score_10": "9.6",
        "match_reason": "Tanitlab construit des produits IA/Data/Cloud et KeplerAI cible fraude, KYC, AML, scoring crédit et conformité. Le profil ENSI, l'ingénierie financière et le PFE Linedata sur les agents IA offrent une adéquation particulièrement forte, même si la dernière annonce Data Scientist demandait deux ans d'expérience.",
        "junior_status": "Oui, surtout stages/PFE; emploi junior non confirmé actuellement",
        "junior_evidence": "Le PFE Book 2025 de Tanitlab documente l'accueil de stagiaires sur des sujets Data/IA. La dernière annonce salariée visible est Senior Data Scientist avec au moins deux ans d'expérience et ne constitue pas une preuve d'ouverture actuelle aux débutants.",
        "active_jobs": "Aucune offre junior active confirmée le 2026-09-25. La publication Senior Data Scientist datant d'environ dix mois demande au moins deux ans d'expérience; elle n'est pas présentée comme active — https://www.linkedin.com/company/tanitlab. Préparer une candidature spontanée ciblée sur un futur besoin junior Data/AI/Cloud ou KeplerAI.",
        "linkedin_contact_name": "Sena BAHRI",
        "linkedin_contact_role": "Co-dirigeante/manager actuelle — Tanitlab; contact publié pour le recrutement Data Science",
        "linkedin_profile": "https://tn.linkedin.com/in/senabahri",
        "contact_verification": "Listée parmi les employés actuels sur la page officielle; l'entreprise a publié son adresse nominative dans l'annonce Data Scientist. Son rôle dirigeant est également corroboré par les informations légales publiques de l'entreprise.",
        "verified_email": "sena@tanitlab.com",
        "email_status": "Adresse vérifiée dans une publication de recrutement officielle de Tanitlab. L'annonce associée est ancienne; envoyer seulement une candidature spontanée et non une candidature au poste Senior.",
        "application_channel": "mailto:sena@tanitlab.com | https://www.linkedin.com/company/tanitlab | formulaire https://www.tanitlab.ai",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "Français",
        "potential_score_100": "76",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Le bureau officiel est à Tunis et le candidat postule localement.",
        "sources": "https://www.linkedin.com/company/tanitlab | https://tn.linkedin.com/in/senabahri | https://www.keplerai.app/ | https://files.thetunisianengineers.com/pfe_books_2025/PFE%20Book%20-%202025%20-%20Tanitlab%20AI.pdf",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — excellente adéquation IA/FinTech, candidature spontanée junior",
        "notes": "Très haute priorité en candidature spontanée. Ne pas utiliser la référence RECRUTDS, liée à une ancienne annonce Senior. Centrer le message sur la valeur métier de l'IA pour le risque, la conformité et les produits financiers, sans empiler trop de détails techniques.",
        "email_subject": "Candidature spontanée — Ingénieur IA/Data junior, profil FinTech ENSI",
        "email_body": "Bonjour Madame Bahri,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, spécialisé en ingénierie financière, je souhaite vous proposer ma candidature spontanée pour une première opportunité en IA, Data ou développement de produits intelligents chez Tanitlab.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier à l'aide d'agents IA. Cette expérience m'a appris à partir d'un besoin métier, concevoir une solution utile et l'intégrer dans un produit existant, tout en gardant à l'esprit la fiabilité, l'expérience utilisateur et la valeur créée.\n\nLe positionnement de Tanitlab et de KeplerAI m'intéresse particulièrement: appliquer l'IA à la fraude, au KYC/AML, au risque de crédit et à la conformité correspond directement à mon double parcours informatique–finance. Je peux contribuer avec Python, machine learning, LLM/RAG, développement logiciel, APIs et bases de données, tout en comprenant les enjeux financiers servis par la technologie.\n\nJe sais que la dernière annonce Data Scientist visible demandait au moins deux ans d'expérience et je ne me présente donc pas comme candidat à ce poste Senior. Je souhaiterais plutôt savoir si un besoin junior actuel ou prochain pourrait correspondre à mon profil.\n\nJe joins mon CV FinTech et reste disponible pour un échange.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Mme Bahri, ingénieur ENSI récemment diplômé et spécialisé en ingénierie financière, j'ai réalisé chez Linedata un PFE sur des agents IA. KeplerAI et ses usages fraude, KYC/AML, risque et conformité correspondent exactement à mon profil IA–FinTech. Ravi de rejoindre votre réseau.",
        "linkedin_followup": "Bonjour Mme Bahri, merci pour la connexion. Je vous ai adressé une candidature spontanée à sena@tanitlab.com, sans me positionner sur l'ancienne offre Senior. Mon profil associe ingénierie logicielle, agents IA et compréhension financière; je serais très intéressé par un futur besoin junior autour de Tanitlab ou KeplerAI.",
    },
    {
        "organization_key": "manager partner software",
        "sector": "Core banking, digital banking, finance postale, microfinance, finance islamique, BI et transformation des systèmes bancaires",
        "target_roles": "Développeur fonctionnel bancaire junior; Business Analyst bancaire junior; Software Engineer FinTech; Consultant fonctionnel SI bancaire; développeur SQL",
        "match_score_10": "9.8",
        "match_reason": "L'offre combine exactement informatique, SQL, compréhension des besoins bancaires et développement sur une plateforme métier. Le diplôme d'ingénieur informatique, la spécialisation financière et le PFE Linedata placent le candidat au cœur du profil recherché; l'IA est un complément de modernisation, pas le sujet principal.",
        "junior_status": "Oui — explicitement débutant",
        "junior_evidence": "L'annonce Développeur Fonctionnel Bancaire indique quatre postes, Temps plein/SIVP, niveau débutant et aucune expérience professionnelle préalable requise; MpSoft forme les collaborateurs sur sa plateforme et ses modules.",
        "active_jobs": "Développeur Fonctionnel Bancaire (Bac+5), Tunis, 4 postes, débutant, Temps plein/SIVP — https://www.tanitjobs.com/job/2038071/developpeur-fonctionnel-bancaire-bac-5/. Le 2026-09-25, la page reste accessible et affiche « Postuler maintenant » ainsi qu'une publication récente, mais sa date d'expiration affichée est le 17/09/2026. Statut technique contradictoire: tenter immédiatement via le bouton et vérifier que le formulaire accepte encore l'envoi avant de considérer la candidature transmise.",
        "linkedin_contact_name": "Khaled TRIKI",
        "linkedin_contact_role": "Fondateur et PDG — Manager Partner Software (MpSoft)",
        "linkedin_profile": "https://tn.linkedin.com/in/khaled-triki-b15aa134",
        "contact_verification": "Fondateur/PDG actuel depuis 2003, confirmé par son profil public et la page officielle de MpSoft. Aucun Talent Acquisition actuel suffisamment fiable n'a été trouvé.",
        "verified_email": "Contact@mpsoftgroup.com",
        "email_status": "Adresse générale affichée sur le site officiel actuel. Le portail TanitJobs reste le canal prioritaire pour l'offre; l'email sert de sauvegarde ou de candidature spontanée si le formulaire refuse l'envoi.",
        "application_channel": "https://www.tanitjobs.com/job/2038071/developpeur-fonctionnel-bancaire-bac-5/ | mailto:Contact@mpsoftgroup.com",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "Français",
        "potential_score_100": "94",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Le poste et le siège concernés se trouvent à Tunis, Les Berges du Lac I.",
        "sources": "https://www.tanitjobs.com/job/2038071/developpeur-fonctionnel-bancaire-bac-5/ | https://mpsoftgroup.com/ | https://www.linkedin.com/company/mpsoft-corebanking | https://tn.linkedin.com/in/khaled-triki-b15aa134",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — correspondance exceptionnelle; bouton de candidature actif mais date d'expiration contradictoire",
        "notes": "Priorité immédiate. Essayer d'abord le bouton TanitJobs et conserver une capture/confirmation. Si le formulaire est fermé, envoyer l'email le même jour en expliquant brièvement que la page restait accessible. Ne pas négocier le salaire dans le premier message. Mettre SQL, compréhension bancaire, apprentissage rapide et PFE Linedata au premier plan.",
        "email_subject": "Candidature — Développeur Fonctionnel Bancaire junior (Bac+5)",
        "email_body": "Bonjour,\n\nJe souhaite vous présenter ma candidature au poste de Développeur Fonctionnel Bancaire junior chez MpSoft. Récemment diplômé ingénieur en informatique de l'ENSI et spécialisé en ingénierie financière, mon parcours correspond directement à la double dimension métier et technique de cette fonction.\n\nLors de mon PFE chez Linedata, j'ai travaillé sur la modernisation d'un produit financier grâce à des agents IA. Au-delà de la technologie, cette expérience m'a appris à comprendre un besoin financier, le structurer puis le traduire en fonctionnalités intégrées à un produit existant. Je maîtrise SQL et les bases de données, ainsi que Python, Java, C++, les APIs et le développement logiciel.\n\nJe suis particulièrement motivé par la possibilité de travailler sur le crédit, les dépôts, le reporting et le digital banking, tout en montant rapidement en compétence sur votre plateforme low-code et vos modules de core banking. L'absence d'expérience exigée et l'accompagnement annoncé correspondent au cadre dans lequel je pourrai apprendre vite et produire une réelle valeur métier.\n\nLa page TanitJobs affiche encore le bouton de candidature, mais également une date d'expiration au 17 septembre. Je vous adresse donc mon CV afin de ne pas manquer l'opportunité si le recrutement des quatre profils est toujours en cours, ou pour un besoin junior équivalent.\n\nJe reste disponible pour un entretien.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour M. Triki, ingénieur ENSI récemment diplômé et spécialisé en ingénierie financière, je candidate au rôle Développeur Fonctionnel Bancaire. Mon PFE chez Linedata associait besoin financier, logiciel et agents IA. Le core banking MpSoft correspond fortement à mon profil. Ravi de vous rejoindre.",
        "linkedin_followup": "Bonjour M. Triki, merci pour la connexion. J'ai tenté la candidature TanitJobs au poste Développeur Fonctionnel Bancaire et envoyé mon CV à l'adresse officielle, car la page affiche encore « Postuler » malgré une date d'expiration contradictoire. Mon profil ENSI + ingénierie financière, SQL et PFE Linedata correspond directement au rôle.",
    },
    {
        "organization_key": "na soft",
        "sector": "Logiciels FinTech, trading en ligne, gestion de fonds et données financières, cloud, modernisation applicative, NOC/SOC",
        "target_roles": "Ingénieur logiciel FinTech junior; développeur web/mobile; développeur Java/Python; Data/AI Engineer junior; analyste fonctionnel financier; Cloud/DevOps junior",
        "match_score_10": "9.4",
        "match_reason": "NA Soft développe des applications de trading, fonds, données boursières et reporting, avec modernisation logicielle et cloud. Le parcours ENSI + ingénierie financière + PFE Linedata est directement pertinent. L'entreprise emploie aussi des ingénieurs travaillant sur IA générative et assistants financiers, ce qui renforce l'adéquation.",
        "junior_status": "Oui, historiquement; besoin actuel non confirmé",
        "junior_evidence": "Des profils diplômés récents et stagiaires sont visibles chez Network Associates/NA Soft, et d'anciennes annonces ont concerné le développement web. Aucune annonce junior actuelle propre à NA Soft n'a toutefois été confirmée le 2026-09-25.",
        "active_jobs": "Aucune offre logiciel/Data/IA active propre à NA Soft confirmée le 2026-09-25. Network Associates, société mère, publie actuellement un poste de comptable qui ne correspond pas au candidat; il ne faut pas le citer comme opportunité IT. La démarche recommandée est une candidature spontanée FinTech/logiciel via l'adresse officielle de NA Soft.",
        "linkedin_contact_name": "Meriem Ben Hajji",
        "linkedin_contact_role": "Ingénieure logiciel Full-Stack et IA générative actuelle — Network Associates/NA Soft",
        "linkedin_profile": "https://tn.linkedin.com/in/meriem-ben-hajji-2970b1207",
        "contact_verification": "Profil actuel chez Network Associates; ses projets publics portent sur STB Finance, les données boursières et un agent IA de gestion de fonds. C'est un contact technique très pertinent, pas une recruteuse. La page officielle de la société mère constitue le canal institutionnel complémentaire.",
        "verified_email": "contact@nas-it.com",
        "email_status": "Adresse générale affichée sur le site officiel de NA Soft. devsupport@nas-it.com est réservé au support et mbelhaj@nas-it.com au support applicatif; ils ne sont pas utilisés pour recruter.",
        "application_channel": "mailto:contact@nas-it.com | https://www.nasoft.net/ | page société mère https://www.linkedin.com/company/network-associates",
        "recommended_cv": "CV_ATS_Fintech.pdf",
        "language": "Français",
        "potential_score_100": "75",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Le siège NA Soft concerné est aux Berges du Lac, Tunis.",
        "sources": "https://www.nasoft.net/ | https://www.networkassociates.tn/ | https://www.linkedin.com/company/network-associates | https://tn.linkedin.com/in/meriem-ben-hajji-2970b1207 | https://play.google.com/store/apps/details?id=com.nas.mmc.bnac",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — excellente adéquation FinTech/logiciel, aucune offre technique active confirmée",
        "notes": "Très haute priorité en candidature spontanée. Le message LinkedIn à Meriem doit demander une orientation et non une décision de recrutement. Insister sur le parallèle entre le PFE Linedata et leurs produits financiers/agents IA, sans prétendre connaître leur architecture interne.",
        "email_subject": "Candidature spontanée — Ingénieur logiciel FinTech / IA junior ENSI",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l'ENSI, avec une spécialisation en ingénierie financière, je souhaite proposer ma candidature spontanée pour une première opportunité en développement logiciel, Data ou IA appliquée aux produits financiers chez NA Soft.\n\nMon PFE chez Linedata a porté sur la modernisation d'un produit financier à l'aide d'agents IA. J'y ai appris à comprendre les besoins des utilisateurs métier, concevoir une solution intelligente et l'intégrer proprement à une application existante. Je maîtrise notamment Python, Java, C++, le développement full-stack et mobile, SQL, les APIs, les bases de données, le machine learning et les LLM.\n\nVos solutions de trading en ligne, de gestion de fonds, de données financières et de modernisation applicative correspondent directement à mon double profil informatique–finance. Je souhaite mettre l'IA au service d'objectifs concrets — meilleure exploitation des données, automatisation utile, fiabilité et évolution des produits — sans perdre de vue les exigences du métier financier.\n\nJe n'ai pas identifié d'offre technique actuellement ouverte; ma démarche est donc une candidature spontanée pour un besoin junior présent ou futur. Je joins mon CV FinTech et reste à votre disposition pour un échange.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Meriem, ingénieur ENSI récemment diplômé et spécialisé en ingénierie financière, mon PFE Linedata portait sur des agents IA pour un produit financier. Vos projets STB Finance et assistant IA de gestion de fonds sont très proches de mon profil. J'aimerais rejoindre votre réseau et suivre les besoins NA Soft.",
        "linkedin_followup": "Bonjour Meriem, merci pour la connexion. J'ai envoyé une candidature spontanée à contact@nas-it.com pour un rôle junior logiciel, Data ou IA FinTech. Votre parcours chez NA Soft, notamment STB Finance et l'agent IA de gestion de fonds, m'a confirmé la pertinence de cette démarche. Pourriez-vous m'indiquer l'équipe ou la personne qui examine ce type de profil ?",
    },
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(RECORDS[0]))
        writer.writeheader()
        writer.writerows(RECORDS)
    print(f"Wrote {len(RECORDS)} records to {OUT}")


if __name__ == "__main__":
    main()
