#!/usr/bin/env python3
"""Verified research batch checked on 2026-09-25."""
from __future__ import annotations
import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "verified_batches" / "batch_2026_09_25_11.csv"

RECORDS = [
    {
        "organization_key": "it network consulting",
        "sector": "Conseil IT, réseaux et infrastructure — activité exacte peu documentée publiquement",
        "target_roles": "Ingénieur systèmes/réseaux junior; Cloud/DevOps junior; cybersécurité junior; support et intégration IT",
        "match_score_10": "6.0",
        "match_reason": "Le socle informatique, Linux, développement et cybersécurité peut convenir à une société de conseil réseaux, mais aucun portefeuille de services, stack ni besoin actuel n'a pu être confirmé. L'IA et la FinTech ne semblent pas être le cœur public de l'activité.",
        "junior_status": "Non vérifiable",
        "junior_evidence": "Aucune annonce junior, stage ou PFE attribuable avec certitude à cette société n'a été trouvée.",
        "active_jobs": "Aucune offre active attribuable avec certitude à IT NETWORK CONSULTING n'a été trouvée le 2026-09-25.",
        "linkedin_contact_name": "Non trouvé/non vérifiable",
        "linkedin_contact_role": "Aucun recruteur ou responsable actuel univoque identifié",
        "linkedin_profile": "Non trouvé/non vérifiable",
        "contact_verification": "Les recherches renvoient des homonymes et résultats génériques; aucun profil n'est fourni pour éviter une mauvaise personne.",
        "verified_email": "Aucun email public vérifié",
        "email_status": "Contact@it-nc.net figure dans le CSV, mais n'a pas été retrouvé sur une source publique officielle actuelle; ne pas l'automatiser avant vérification.",
        "application_channel": "Non trouvé/non vérifiable",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "34",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Adresse source au Manar 2, Tunis.",
        "sources": "Recherches exactes Google/Bing/LinkedIn du 2026-09-25; aucun site ou profil officiel univoque retrouvé",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — présence publique insuffisante; aucun envoi sûr actuellement",
        "notes": "Priorité faible tant qu'un site officiel, une page société actuelle ou un contact interne n'est pas identifié. Conserver le texte ci-dessous, mais ne pas envoyer automatiquement à l'adresse du CSV.",
        "email_subject": "Candidature spontanée — Ingénieur informatique junior",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite proposer ma candidature spontanée pour une première opportunité en ingénierie IT, systèmes, cloud, cybersécurité ou développement logiciel.\n\nMon PFE chez Linedata a porté sur la modernisation d’un produit financier à l’aide d’agents IA. Il m’a permis de renforcer ma capacité à comprendre un besoin, concevoir une solution puis l’intégrer dans un environnement existant. Je maîtrise Python, Java, C++, Linux, les APIs, SQL, les bases de données et le développement full-stack, avec des connaissances en cloud et cybersécurité.\n\nJe serais heureux de mettre ce socle polyvalent au service de vos projets et de monter rapidement en compétence sur vos outils. Je joins mon CV et reste disponible pour un échange.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Aucun profil personnel fiable identifié — ne pas envoyer d’invitation à un homonyme.",
        "linkedin_followup": "À utiliser seulement après identification certaine d’un responsable actuel : Bonjour, merci pour la connexion. Je recherche une première opportunité en ingénierie IT, cloud, cybersécurité ou logiciel. Pourriez-vous m’indiquer le bon canal pour transmettre mon CV à IT NETWORK CONSULTING ?",
    },
    {
        "organization_key": "o3 tools software",
        "sector": "Conseil en gestion et services environnementaux; société enregistrée sous une dénomination software",
        "target_roles": "Développeur logiciel/Data junior pour outils environnementaux; analyste de données; automatisation et reporting",
        "match_score_10": "4.8",
        "match_reason": "Le candidat pourrait contribuer à des outils de données ou d'automatisation, mais la seule activité officielle trouvée concerne le conseil aux gestionnaires de services environnementaux et le conseil de gestion. Aucun produit logiciel, projet IA ou recrutement technique actuel n'est documenté.",
        "junior_status": "Non vérifiable",
        "junior_evidence": "Aucune annonce junior ou politique de recrutement publique retrouvée.",
        "active_jobs": "Aucune offre active confirmée le 2026-09-25.",
        "linkedin_contact_name": "Ahmed Khalifa El Khalil",
        "linkedin_contact_role": "Gérant indiqué lors de la constitution en 2019 — statut actuel non vérifiable",
        "linkedin_profile": "Aucun profil LinkedIn univoque trouvé",
        "contact_verification": "Le nom provient du Journal officiel de 2019; il ne suffit pas à confirmer une fonction actuelle. Ne pas cibler une personne sans nouvelle vérification.",
        "verified_email": "Aucun email public vérifié",
        "email_status": "gws.sdridi@gmail.com figure dans le CSV mais n'apparaît pas dans une source publique actuelle de recrutement; ne pas utiliser automatiquement.",
        "application_channel": "Non trouvé/non vérifiable",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "22",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "Siège légal retrouvé à Ariana.",
        "sources": "https://lake.jort.tn/annonces-legales/fr/2019/017.pdf",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — société retrouvée, activité technique et recrutement non démontrés",
        "notes": "Faible priorité. Ne pas envoyer avant d'identifier un site, un canal ou un responsable actuel.",
        "email_subject": "Candidature spontanée — Ingénieur informatique junior",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, je souhaite manifester mon intérêt pour un éventuel besoin junior en développement logiciel, traitement de données ou automatisation chez O3 Tools Software.\n\nMon PFE chez Linedata a porté sur la modernisation d’un produit financier à l’aide d’agents IA. Je maîtrise Python, Java, C++, le développement full-stack, les APIs, SQL, les bases de données et le machine learning. Je pourrais mettre ces compétences au service d’outils facilitant l’analyse, le suivi et la prise de décision dans vos missions de conseil.\n\nJe n’ai trouvé aucune offre technique actuellement ouverte et vous contacte donc uniquement à titre spontané. Je serais ravi d’échanger si un besoin correspondant existe.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Aucun profil LinkedIn actuel suffisamment fiable — ne pas contacter un homonyme.",
        "linkedin_followup": "Bonjour, merci pour la connexion. Je recherche une première opportunité en logiciel, Data ou automatisation. Pourriez-vous me confirmer l’activité technique actuelle d’O3 Tools Software et le canal approprié pour une candidature spontanée ?",
    },
    {
        "organization_key": "lisic ulco",
        "sector": "Recherche universitaire en IA, machine learning, vision, signal, optimisation et ingénierie des connaissances",
        "target_roles": "Ingénieur d'études/recherche IA; Research Software Engineer; doctorant; stage Master 2",
        "match_score_10": "7.7",
        "match_reason": "Python, IA/ML, C++ et développement logiciel correspondent aux travaux du LISIC, notamment XAI, vision et traitement des données. Les voies visibles sont toutefois académiques: stages Master 2, ATER et Maître de conférences, et non un premier poste logiciel généraliste.",
        "junior_status": "Oui, principalement stages et contrats académiques",
        "junior_evidence": "Le LISIC publie des stages Master 2 et l'ULCO a recruté en 2026 un ATER lié à l'apprentissage automatique, l'IA, le signal et la vision. Ces campagnes sont closes et certaines exigent un statut étudiant ou académique.",
        "active_jobs": "Aucune offre junior adaptée confirmée ouverte le 2026-09-25. L'ATER LISIC a clôturé le 19/06/2026 — https://recrutements-enseignants.extranet.univ-littoral.fr/Ater/poste/500. Le poste Maître de conférences XAI a clôturé le 03/04/2026. Le stage Master 2 2026 ne constitue pas un emploi pour un diplômé non inscrit.",
        "linkedin_contact_name": "LISIC / Université du Littoral Côte d’Opale",
        "linkedin_contact_role": "Canal institutionnel; aucun recruteur personnel actuel propre au laboratoire identifié",
        "linkedin_profile": "https://www.linkedin.com/school/ulco-univ/",
        "contact_verification": "La page institutionnelle ULCO est actuelle. L'adresse de Gaëlle Compiègne est le contact officiel du laboratoire, pas une adresse RH.",
        "verified_email": "gaelle.compiegne@univ-littoral.fr",
        "email_status": "Adresse publiée sur la page officielle d'accès/contact du LISIC; à utiliser pour demander le bon encadrant ou canal, pas comme candidature RH automatique.",
        "application_channel": "https://lisic-prod.univ-littoral.fr/acces/ | https://www.univ-littoral.fr/universite/travailler-a-lulco/",
        "recommended_cv": "CV_ATS_EN.pdf",
        "language": "Français",
        "potential_score_100": "30",
        "foreign_employee_status": "Non vérifiable",
        "foreign_employee_evidence": "Aucune offre junior correspondante ne précise visa ou relocation. Les stages exigent normalement un statut étudiant et une convention; les postes académiques suivent des conditions nationales spécifiques.",
        "sources": "https://lisic-prod.univ-littoral.fr/acces/ | https://recrutements-enseignants.extranet.univ-littoral.fr/Ater/poste/500 | https://fr.linkedin.com/posts/ai-scientist_recrutement-2026-rejoignez-le-lisic-poste-activity-7434933564984492032-U3vr | https://www-lisic.univ-littoral.fr/~renaud/Cours/StagesM2/stageM2calice.pdf",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — voies académiques closes ou incompatibles avec un diplômé hors statut étudiant",
        "notes": "Faible priorité pour l'emploi immédiat. Écrire seulement pour demander un futur contrat d'ingénieur d'études/recherche accessible à un diplômé international.",
        "email_subject": "Demande d’information — futur contrat junior IA / logiciel de recherche",
        "email_body": "Bonjour Madame Compiègne,\n\nRécemment diplômé ingénieur en informatique de l’ENSI en Tunisie, je souhaiterais savoir si le LISIC prévoit de futurs contrats d’ingénieur d’études ou de recherche junior autour de l’IA, du machine learning ou du développement logiciel scientifique.\n\nMon PFE chez Linedata a porté sur la modernisation d’un produit financier à l’aide d’agents IA. Mon profil réunit Python, Java, C++, machine learning, LLM/RAG, APIs et bases de données, avec une forte capacité à relier expérimentation et intégration logicielle.\n\nJ’ai bien noté que les campagnes ATER et Maître de conférences 2026 sont closes et que les stages Master 2 supposent un statut étudiant. Je ne souhaite donc pas candidater à tort à ces dispositifs. Pourriez-vous m’indiquer si un futur contrat distinct peut convenir à un jeune ingénieur international déjà diplômé, et vers quel responsable scientifique m’orienter ?\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour, jeune diplômé ingénieur ENSI, mon PFE portait sur des agents IA intégrés à un produit. Les travaux du LISIC en IA/ML et logiciel scientifique m’intéressent. Je souhaite suivre de futurs contrats d’ingénieur de recherche accessibles aux diplômés internationaux.",
        "linkedin_followup": "Bonjour, merci pour la connexion. Les campagnes 2026 visibles étant closes ou réservées à des statuts académiques, je cherche seulement à identifier un futur contrat d’ingénieur d’études/recherche junior. J’ai écrit au contact institutionnel du LISIC pour demander le bon encadrant et les conditions d’éligibilité internationale.",
    },
    {
        "organization_key": "ovidius ai b v",
        "sector": "Conseil et réalisation de systèmes GenAI, agents IA, RAG, automatisation n8n et intégration d'IA en environnements réglementés",
        "target_roles": "Junior AI Engineer; Agentic AI Developer; LLM/RAG Engineer; Python/API Developer; AI Automation Engineer",
        "match_score_10": "9.1",
        "match_reason": "L'IA agentique, les LLM/RAG, les APIs, Python et l'expérience Linedata en environnement financier réglementé sont très proches des projets d'Ovidius. L'obstacle majeur est que les besoins publics récents sont orientés profils expérimentés et désormais basés aux États-Unis.",
        "junior_status": "Non — pas pour les besoins publics consultés",
        "junior_evidence": "L'ancienne offre Multi-Agent Developer demandait 5+ ans de développement. L'offre actuelle de Project Manager exige une expérience réelle en environnements réglementés et une présence aux États-Unis, malgré l'étiquette LinkedIn entry level.",
        "active_jobs": "Project Manager (Regulated Environments), contrat/fractional, États-Unis uniquement — https://www.linkedin.com/jobs/view/project-manager-regulated-environments-%40-ovidius-ai-at-ovidius-ai-b-v-4434213311. Offre active mais non adaptée: rôle de delivery expérimenté et « US-based is a must ». Aucun poste AI Engineer junior ouvert confirmé.",
        "linkedin_contact_name": "Owen Boesveld",
        "linkedin_contact_role": "Founder & CEO — Ovidius AI",
        "linkedin_profile": "https://www.linkedin.com/in/owenboesveld",
        "contact_verification": "Fondateur actuel; son profil annonce le recrutement US et précise qu'Ovidius a déplacé ses opérations des Pays-Bas vers les États-Unis en 2026.",
        "verified_email": "Aucun email public de recrutement vérifié",
        "email_status": "info@ovidiusmarketing.com du CSV appartient à l'ancienne identité/domaine et n'est pas retenu. Le site actuel propose un formulaire commercial, pas une candidature carrière.",
        "application_channel": "https://www.linkedin.com/company/ovidius-ai-b-v/ | contact direct avec le fondateur uniquement pour demander une future ouverture internationale",
        "recommended_cv": "CV_ATS_Fintech_EN.pdf",
        "language": "Anglais",
        "potential_score_100": "39",
        "foreign_employee_status": "Non pour l'offre actuelle",
        "foreign_employee_evidence": "L'offre Project Manager indique explicitement que le candidat doit être basé aux États-Unis, sans exception. Le fondateur précise que les opérations ont déménagé aux États-Unis; aucune politique internationale n'est publiée pour un futur poste d'ingénieur.",
        "sources": "https://www.ovidius.ai/ | https://www.linkedin.com/in/owenboesveld | https://www.linkedin.com/jobs/view/project-manager-regulated-environments-%40-ovidius-ai-at-ovidius-ai-b-v-4434213311 | https://pl.linkedin.com/jobs/view/ai-multi-agent-developer-at-ovidius-marketing-b-v-4065507304",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — excellente adéquation technique, mais besoins expérimentés et implantation US obligatoire",
        "notes": "Faible priorité immédiate malgré l'excellent fit technique. Ne pas postuler au Project Manager. Invitation courte au fondateur pour suivre une future mission AI Engineer remote/internationale.",
        "email_subject": "Future Junior AI Engineer Opportunities — Agentic AI & Regulated Finance",
        "email_body": "Dear Mr Boesveld,\n\nI am a recent Computer Engineering graduate from ENSI in Tunisia, specialised in Financial Engineering, and I am interested in future junior AI engineering opportunities at Ovidius AI.\n\nMy final-year project at Linedata focused on modernising a financial product with AI agents. I worked from the business need through agent workflows and their integration into an existing application. My background includes Python, LLM/RAG systems, APIs, databases, full-stack development and machine learning.\n\nOvidius stands out to me because you deploy agentic systems in regulated environments where governance, documentation and business value matter as much as the model. This is closely aligned with my financial-software experience.\n\nI understand that the current Project Manager role is US-based and requires experience I do not yet claim, and that the former Multi-Agent Developer posting was senior. I am therefore not applying to either role. I would simply be glad to stay informed about a future junior or internationally remote AI Engineer opening.\n\nKind regards,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Hello Owen, I’m a recent ENSI Computer Engineering graduate specialised in Financial Engineering. My Linedata project used AI agents to modernise a regulated financial product. Ovidius’ focus on production agents, RAG and compliance strongly matches my profile. Glad to follow future junior roles.",
        "linkedin_followup": "Thank you for connecting. I understand your current PM role is US-only and experienced, so I am not applying to it. My interest is in a future junior AI Engineer role combining agents, RAG, APIs and regulated business workflows. If Ovidius later considers international remote talent, I would be grateful to be kept in mind.",
    },
    {
        "organization_key": "pyxis it",
        "sector": "Telecom Data Intelligence, IA, agents, analytics prédictive, automatisation, logiciel, cloud et DevOps",
        "target_roles": "Junior AI/ML Engineer; Data Engineer; Software Engineer; Agentic AI Developer; DevOps/Cloud Engineer; Data Analyst télécom",
        "match_score_10": "9.2",
        "match_reason": "La nouvelle offre de valeur Pyxis associe données télécom, analytics, AI agents et automatisation; elle correspond très bien au PFE agentique et au socle logiciel/Data. Le candidat n'a pas encore d'expérience télécom, mais son profil polyvalent peut s'y transférer rapidement.",
        "junior_status": "Oui — fortement suggéré par les recrutements observés",
        "junior_evidence": "Plusieurs employés actuels sont de récents diplômés ou encore élèves ingénieurs; un profil public annonce avoir rejoint Pyxis comme Software Developer après son diplôme. Cela prouve une ouverture réelle aux profils précoces, sans confirmer une vacance actuelle.",
        "active_jobs": "Aucune offre active publiée sur la nouvelle page officielle au 2026-09-25. La page PYXIS IT a été lancée récemment et présente ORION, l'IA, les agents, l'analytics et l'automatisation; privilégier une candidature spontanée — https://uk.linkedin.com/company/pyxis-it-ltd.",
        "linkedin_contact_name": "Sinda Louil",
        "linkedin_contact_role": "Platform & Site Reliability Engineer / Integration Team Lead — Pyxis IT",
        "linkedin_profile": "https://tn.linkedin.com/in/synda-louil",
        "contact_verification": "Profil actuel, localisé au Centre Urbain Nord, avec une fonction technique de lead. Aucun recruteur actuel n'a été identifié; demander une orientation, pas une décision de recrutement.",
        "verified_email": "Aucun email public de recrutement vérifié",
        "email_status": "contact@pyxis.com.tn du CSV n'est pas affiché sur la version publique consultable du site officiel; ne pas l'étiqueter vérifié. Le canal LinkedIn société est prioritaire.",
        "application_channel": "https://uk.linkedin.com/company/pyxis-it-ltd | https://pyxis.com.tn/",
        "recommended_cv": "CV_ATS.pdf",
        "language": "Français",
        "potential_score_100": "78",
        "foreign_employee_status": "Sans objet — Tunisie",
        "foreign_employee_evidence": "La candidature vise l'équipe de Tunis/Centre Urbain Nord, même si la nouvelle page affiche aussi un siège au Royaume-Uni.",
        "sources": "https://uk.linkedin.com/company/pyxis-it-ltd | https://pyxis.com.tn/ | https://tn.linkedin.com/in/synda-louil | https://tn.linkedin.com/in/hbechir | https://tn.linkedin.com/in/arij-belmabrouk-7a1abb253/fr",
        "checked_date": "2026-09-25",
        "verification_status": "Vérifié — excellente adéquation et ouverture junior observée, aucune vacance actuelle publiée",
        "notes": "Très haute priorité en candidature spontanée. Contacter d'abord Sinda pour demander le bon canal; joindre le CV seulement après réponse ou via un canal confirmé. Souligner la capacité à transposer les agents IA et la Data du secteur financier vers l'intelligence télécom.",
        "email_subject": "Candidature spontanée — Ingénieur IA/Data/Software junior ENSI",
        "email_body": "Bonjour,\n\nRécemment diplômé ingénieur en informatique de l’ENSI, avec une spécialisation en ingénierie financière, je souhaite proposer ma candidature spontanée pour une première opportunité en IA, Data ou développement logiciel chez Pyxis IT.\n\nMon PFE chez Linedata a porté sur la modernisation d’un produit financier à l’aide d’agents IA. J’ai travaillé sur la compréhension du besoin, la conception de workflows intelligents et leur intégration dans un produit existant. Je maîtrise Python, Java, C++, le développement full-stack, les APIs, SQL et les bases de données, le machine learning, les LLM/RAG ainsi que les bases du cloud et du DevOps.\n\nLe positionnement récent de Pyxis autour de Telecom Data Intelligence, ORION, l’analytics prédictive, les agents IA et l’automatisation m’intéresse particulièrement. Même si mon expérience métier initiale est financière, les mêmes compétences — exploiter des données complexes, produire des prédictions utiles et intégrer l’IA à des workflows réels — sont directement transférables aux télécoms.\n\nJe n’ai pas trouvé d’offre actuellement ouverte et vous contacte donc en toute transparence à titre spontané. Je serais ravi d’échanger sur un besoin junior présent ou prochain.\n\nBien cordialement,\nMohamed Oussema Bahloul",
        "linkedin_invitation": "Bonjour Sinda, ingénieur ENSI récemment diplômé, mon PFE Linedata portait sur des agents IA intégrés à un produit. Le nouveau positionnement Pyxis autour d’ORION, Telecom Data Intelligence, analytics et AI agents correspond fortement à mon profil. Pourriez-vous m’orienter vers le bon canal junior ?",
        "linkedin_followup": "Bonjour Sinda, merci pour la connexion. Je souhaite proposer ma candidature spontanée pour un rôle junior IA, Data ou Software chez Pyxis. Mon expérience initiale est FinTech, mais mes travaux sur agents IA, données complexes, APIs et intégration produit sont très transférables à l’intelligence télécom. Quel canal ou interlocuteur me conseillez-vous ?",
    },
]

with OUT.open("w", encoding="utf-8-sig", newline="") as handle:
    writer = csv.DictWriter(handle, fieldnames=list(RECORDS[0]))
    writer.writeheader()
    writer.writerows(RECORDS)
print(f"Wrote {len(RECORDS)} records to {OUT}")
